### ISSUE TITLE
Enhance nntrainer inference filter 

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#1005]
### Regarding the implementation (#1010)

1. Make it work without giving in/out dimension (as it is stated inside the model description)
1. Giving in/out dimension is possible
1. Don't copy input but let nnstreamer allocate memory
1. Dynamic output dimension calculation from given input (this is needed because we accept number of batches)

### Regarding the reliability (waiting for nnstreamer/nnstreamer#3128)

1. Unittest for the inference wrapper
1. Templated sub-plugin test
1. Integrated test nnstreamer with singleshot api
1. Integrated test with gstreamer

**Comment by kparichay** [comment]
> Giving in/out dimension is possible but batch is ignored (@kparichay, any opinions?)

Lets the follow the semantics used by nnstreamer for tflite extension.
From nntrainer point of view, the batch specified in the data dimensions will be handled by the `model::inference` method.

**Comment by kparichay** [comment]
Also, you can consider updating the tensor-filter plugin to use the c++ API headers, whereever possible.

**Comment by zhoonit** [comment]
#1010 handles the issue.

Yes, I made it to handle as pretty much other extension does.
I didn't use ccapi for compatibility reason, but it can be almost directly translated :)
