### ISSUE TITLE
layer::forwarding does more than it should

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nntrainer#101]
There are two class functions for layers named forwarding - 
First - 
```
virtual Tensor forwarding(Tensor in, int &status) = 0;
```
Second - 
```
virtual Tensor forwarding(Tensor in, Tensor output, int &status) = 0;
```

As far as I can understand, the implementation for the second declaration does more than it should in some cases while not in others.
- For fc layer, it also calculates the loss and updates it in case its the last layers for fc layer.
- For bn layer, it behaves the same as the first declaration - is this intended?

IMO, each layer should just forward itself. And NeuralNet::forwarding should call/perform loss forwarding (if needed). This would also introduce a loss class (just like layer class).

If you think this is desirable, I would be more than happy to send a patch.

**Comment by jijoongmoon** [comment]
I agree with you. Those are in the list to improve.
. The reason of the existence of second forwarding function, we want to get the output and evaluate the accuracy for the validation & testing. It would be great if we have more concise solution for it. 
. Talking about the bn_layer, it is in the middle of develop. It is not fully implemented. Any help is great.
. I think everything is always desirable and worthy. I'm looking forward to your patch.

**Comment by kparichay** [comment]
@jijoongmoon 
In the current implementation, each layer has a `CostType`. Further, `FC layer` has its own implementation for loss and cost.
IMO a better strategy would be to have a loss layer. This can incorporate the cost and loss calculation, and work independently with FC/cost.

However, this would require some major changes. So, confirming with you before starting to you. Below is what it would be like:
A new layer named `loss` with corresponding `forwarding` and `backwarding` functions. This would be appended as the last layer, and would allow propagation of cost/loss.

**Comment by jijoongmoon** [comment]
Yes. I agree with you. It would be great. Let's do it.

**Comment by zhoonit** [comment]
@kparichay  FYI, I am working on a little optimization on `fc_layer`. I will make a PR to share a brief concept. It does not need merge though :)

**Comment by kparichay** [comment]
@zhoonit The optimization is good. I will try to move the loss parts out of the layers separately so that they can be reused with conv layers etc.
