### ISSUE TITLE
NNTrainer throws at load

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nntrainer#1012]
NNTrainer AppContext() throws upon loading. Below is that call stack of the throw:
![image](https://user-images.githubusercontent.com/6565775/111109766-b997ea80-859e-11eb-8af8-a08cf1040557.png).

Although the throw is caught, there should not be a throw in the first case.
@zhoonit Can you please check?

**Comment by zhoonit** [comment]
yup :)
