### ISSUE TITLE
Update the ownership policy of weights to prevent possible bugs

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nntrainer#1030]
Currently, the weights are owned by the layer, and the manager keeps a reference. So, if a layer is deleted before the manager is, that leaves the manager with undefined references and there is no way to verify if a reference is valid in c++.

One of the solutions is to directly use shared_ptr for shared ownership. There might be other solutions as well.

**Comment by zhoonit** [comment]
Quick thought

1. we register layer instead of weights to the manager. when we delete layer, we notify manager
2. using `weak_ptr`

**Comment by kparichay** [comment]
> we register layer instead of weights to the manager. when we delete layer, we notify manager

IMO, if you want to register a layer, it must be to the graph. The graph can later provide necessary information to the manager. However, if the user allocates a layer object, the user can reset/delete it as well without the graph knowing it (unless there is a special interface to delete the layer from the graph and it's not a good design IMO) or the graph keeps polling it.

weak_ptr/shared_ptr for shared_ownership solves the above issue as well as the issue of reference_wrapper with a minor overhead.

**Comment by kparichay** [comment]
This is done with layer_context and LayerV2 design. Closing this here.
