### ISSUE TITLE
Rework layer::copy

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#1043]
curretly, layer copy is broken. We will need some policy and copy ctor rework.
Virtual copy constructor is fine (https://www.geeksforgeeks.org/advanced-c-virtual-copy-constructor/)

**Comment by kparichay** [comment]
*::copy is broken. It needs verification at various scenarios (before compile, initialize, train etc). Make this issue generic and track all at once. You also might want to think about when this will be used, and its purpose.

**Comment by kparichay** [comment]
`Layer::copy()` has been deprecated with LayerV2 design. One of the requirements of this function was in Reinforcement Learning where this function was used to copy weights from one model to another. This will now be supported separately with `loadWeights(Model &)` #1341.

@zhoonit Please update this issue if its still valid.

**Comment by zhoonit** [comment]
I think this will stale if we leave this open. let's close this for now and bring it up later :)
