### ISSUE TITLE
devel package and headers need some clean up

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#1063]
1. devel package is not working due to missing header (or unnecessary inclusion at the header file)
2. capi-devel and nntrainer-devel is mixed.

**Comment by kparichay** [comment]
This will be done after or with #986 .

**Comment by zhoonit** [comment]
Cool. I worked a bit with @lhs8928 just to make it work for now. please refer to the PR that hs is about to make

**Comment by zhoonit** [comment]
- loss type definition is included in `networkGraph` but type is defined at `loss_layer.h`

**Comment by jijoongmoon** [comment]
We need to test writing the custom layer and custom optimizer with devel package.

**Comment by kparichay** [comment]
Yes, that will be done as soon as layer refactoring is done (it is delayed in my schedule though)

**Comment by zhoonit** [comment]
- remove parse_util.h from header that would be included.
