### ISSUE TITLE
make backbone property consistent

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#1072]
from api, backbone is loaded from `modelfile=foo.tflite`
from ini, backbone is loaded by `backbone=foo.tflite`

I think we should merge this. Please leave some opinion :)

**Comment by kparichay** [comment]
lets merge to `modelfile=foo.tflite` and add `type=backbone` to specify that the current section is for backbone type layer.

**Comment by jijoongmoon** [comment]
I just wonder.. do we write some notice that explain about the postfix of input file of backbone?? We run the backbone network according to this postfix..

**Comment by kparichay** [comment]
> I just wonder.. do we write some notice that explain about the postfix of input file of backbone?? We run the backbone network according to this postfix..

Do you mean the suffix which is added to all the layers in the backbone?

**Comment by zhoonit** [comment]
It turns out that we have a good reason to sustain current behavior: ini is not a single backbone layer. As extending from ini is not supported, both behavior will be supported.

1. trainable backbone

[section]
backbone=something.ini

2-1. non-trainable backbone

[section]
backbone=something.tflite

2-2. non-trainable backbone

[section]
type=backbone_tflite
backbone=something.tflite
