### ISSUE TITLE
Inference_inout_memory_opt in inference mode

### ISSUE THREAD

**Issue by lhs8928** [nnstreamer/nntrainer#1094]
Problem: Enable inference_inout_memory_opt in inference could make a problem

Cause: If the networks are not flatten which means have a cycle, some of output of layer should be preserved.
For example, in resnet there is a residual output and if the opt is enabled this data could be corrupted.

Solution(?): Check if the layer have a multiple input or output.

**Comment by zhoonit** [comment]
elaborating the yesterday's debugging,
for the resnet, in/out order is not even/odd because the input memory has to be kept to feed the addition layer.

we will need a test for the addition layer inside a model as well.

**Comment by kparichay** [comment]
Memory optimizations have not been tested well with mutli-input/output layers as we didn't have any models using them properly.
This will have to be done soon.
