### ISSUE TITLE
request for validation, fc layer seems to have bug

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#1120]
when fc receives non flattened tensor as input, and input dimension eg) 300:300:3, this should be error.

**Comment by kparichay** [comment]
should it be an error? FC layer just applies matrix multuplication with the last dimension. 
If that dimension mismatches with the weight, then it must be an error.

**Comment by zhoonit** [comment]
in fc, weight_dim is proportional to `input_dim.width()`; but if we were to allow 300:300:3 as an input, shouldn't it be proportionalto `input_dim.getFeatureLen()`?

**Comment by jijoongmoon** [comment]
well, dimension of weight is width x unit .. and the input treat like (channel x height) x width. and the output of fc might be (channel x height) x unit. So the calculation is done as we expected. So matter is that do we have to assume this is error? I think it is now.

**Comment by kparichay** [comment]
> in fc, weight_dim is proportional to `input_dim.width()`; but if we were to allow 300:300:3 as an input, shouldn't it be proportional to `input_dim.getFeatureLen()`?

No, FC layer will not flatten by itself. If flattening has to be done, it will be done with flatten layer (which in this case is not present, otherwise input dimension would not be 300:300:3 but would be 270000)

> well, dimension of weight is width x unit .. and the input treat like (channel x height) x width. and the output of fc might be (channel x height) x unit. So the calculation is done as we expected. So matter is that do we have to assume this is error? I think it is now.

Exactly. IMO, if the width matches with the weight dimension, this should NOT be an error.

**Comment by zhoonit** [comment]
> Exactly. IMO, if the width matches with the weight dimension, this should NOT be an error.

Thanks for the clarification, cross checked with torch and our behavior looks fine, let's close this issue.
