### ISSUE TITLE
[CI] Test fail on i586

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#1125]
referring to https://github.com/nnstreamer/nntrainer/pull/1123, that test is failing.
I found that i586 wasn't tested beforehand. 

verified with commit as old as f41e0bc74761414c3e44fb0d4975bc6191d22b7e . I think it's okay to not test i586 as the number difference is small and it wouldn't affect the behavior of the library.

Leaving this for the record, I am going to disable i586.

```
[   97s] The output from the failed tests:
[   97s] 
[   97s] 17/26 unittest_ccapi                 FAIL           7.05s (exit status 1)
[   97s] 
[   97s] --- command ---
[   97s] 11:33:33 /home/abuild/rpmbuild/BUILD/nntrainer-0.1.1/build/test/ccapi/unittest_ccapi --gtest_output=xml:/home/abuild/rpmbuild/BUILD/nntrainer-0.1.1/build/unittest_nntrainer_profiler.xml
[   97s] --- Listing only the last 100 lines from a long log. ---
[   97s] Unit = 10
[   97s] Type = fully_connected
[   97s] input_layers = inputlayer
[   97s] 
[   97s] #1/1 [ =                    ] 0% ( Training Loss: 2.42675 )
[   97s] #1/1 [ =======              ] 31% ( Training Loss: 5.60378 )
[   97s] #1/1 [ =============        ] 63% ( Training Loss: 5.27162 )
[   97s] #1/1 - Training Loss: 4.43405 >> [ Accuracy: 8.33333% - Validation Loss : 2.96461 ] 
[   97s] ../test/ccapi/unittest_ccapi.cpp:204: Failure
[   97s]       Expected: model->getValidationLoss()
[   97s]       Which is: 2.964613
[   97s] To be equal to: 2.9646113
```

**Comment by myungjoo** [comment]
Be careful, Tizen-emul for armv7l devices may use i586 binaries; thus we may have app developers relying on i586 binaries.
Does the issue occur in armv7l binaries? Is this relative with 32b-64b C types?

**Comment by zhoonit** [comment]
> Be careful, Tizen-emul for armv7l devices may use i586 binaries; thus we may have app developers relying on i586 binaries.
> Does the issue occur in armv7l binaries? Is this related with 32b-64b C types?

This difference are only occure in `tizen-i586`. `tizen-armv7l` does not have this issue.
I am suspecting there are arch specific reason how floating points are calculated inside tizen-i586.

Considering the error propagation, this much error is acceptable, and i586 will be still supported.
fyi) exact one test fails that checks the calculating loss, and the difference is fairly small (2.964613 vs 2.9646113)

**Comment by myungjoo** [comment]
For floating points, use EXPECT_NEAR instead of EXPECT_EQ.

**Comment by zhoonit** [comment]
We are using `EXPECT_FLOAT_EQ`, I'll lower the precision for the test :)
