### ISSUE TITLE
Check preprocess layer

### ISSUE THREAD

**Issue by lhs8928** [nnstreamer/nntrainer#1129]
1. Add on app_context to create layer
2. Add preprocess layer in example
3. Check preprocess layer in backpropagation

**Comment by zhoonit** [comment]
3. -> assure layer does not get backpropagated when there are consecutive non-trainable layers from the input.

**Comment by kparichay** [comment]
3. preprocess layers do not support backpropagation. Just ensure that their trainable defaults to false, and setting it true is not allowed. Once done, graph ensures that non-trainable layers are not backpropagated when placed together at the start of the graph (check setting and usage of `skip_non_trainable_layers` in graph).
