### ISSUE TITLE
Add permute layer

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#1154]
Add transpose layer somewhat similar to https://www.tensorflow.org/api_docs/python/tf/keras/layers/Permute

This is needed if we are to extract a feature from different format and train native nntrainer layer.

**Comment by jijoongmoon** [comment]
Then we need to distinguish permute and transpose with batch support.

**Comment by zhoonit** [comment]
> Then we need to distinguish permute and transpose with batch support.

Yes, I think for permute layer without batch semantic is more appropriate.
FYI) This was request from TPL

**Comment by kparichay** [comment]
@zhoonit Can you please describe what is permute layer.

**Comment by zhoonit** [comment]
> @zhoonit Can you please describe what is permute layer.

Updated doc

**Comment by zhoonit** [comment]
Creating Permute layer done
