### ISSUE TITLE
VOC from AIC : requirements

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nntrainer#1176]
1. [x] Concat layer support for INI and test the concat layer in a model @zhoonit 
   1. input_layers = A + B (current support only for A, B) (delayed)
   2. update realizeMultiInputType() (done)
   3. Test in a model (done)
   4. Maybe add unittest as well (done)

2. [x]  Model to simulate multiple inputs
    1. Combine the inputs  in the dataset and split  the inputs in the models
    2. corresponding unittests and app tests.

Moved generic multi inputs/outputs support to #1253 as the current requirements are completed with simulating multiple inputs for the model with a split layer.

**Comment by kparichay** [comment]
@jijoongmoon Please check this once.

**Comment by jijoongmoon** [comment]
We need to check if they need multiple datasets.

**Comment by zhoonit** [comment]
Related issue https://github.com/nnstreamer/nntrainer/issues/239

**Comment by kparichay** [comment]
@zhoonit Is concat layer part done, including support of  `input_layers=A,B` will insert a concat layer with A,B?

**Comment by zhoonit** [comment]
> @zhoonit Is concat layer part done, including support of `input_layers=A,B` will insert a concat layer with A,B?

Concat is verified and supported for their requirement.

There are number of things to be done to complete this, if we are not duck tapping it. I think, though, AIC requirement is satisfied, so can be dealt separately.

**Comment by kparichay** [comment]
Please open a new issue listing out the things to be done then.

**Comment by kparichay** [comment]
Closing issue as the current requirements are met. Can re-opened if some bugs arise or create new issue for further requirements.
