### ISSUE TITLE
Faulty unittests being passed due to unittest bug

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nntrainer#1180]
Below are the listed faulty unittests which were passing because of the unittest bugs and must be resolved soon:
- nntrainer_FullyConnectedLayer_TFmatch.DISABLED_forwarding_backwarding_00_p
- nntrainer_Conv2DLayer.DISABLED_backwarding_01_p
- nntrainer_Conv2DLayer.DISABLED_backwarding_02_p
- nntrainer_Conv2DLayer.DISABLED_backwarding_03_p
- nntrainer_Conv2DLayer.DISABLED_backwarding_04_p
- nntrainer_EmbeddingLayer.DISABLED_forwarding_02_p

**Comment by kparichay** [comment]
@jijoongmoon Please resolve `nntrainer_EmbeddingLayer.DISABLED_forwarding_02_p`
@zhoonit Please resolve `nntrainer_Conv2DLayer.DISABLED_backwarding_0*_p`
I will take care of the `nntrainer_FullyConnectedLayer_TFmatch.DISABLED_forwarding_backwarding_00_p`

**Comment by zhoonit** [comment]
#1558 will handle this issue so how about closing this issue?

**Comment by kparichay** [comment]
let's replicate these failing unittests with #1558. Once it is done, this can be closed.
