### ISSUE TITLE
neuralnet get orphaned while running test

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#1322]
When running test and exit the program, the training routine gets orphaned and keep try training,

this should be handled with databuffer refactoring.

steps to reproduce.
```bash
$ meson build
$ cd build
$ meson test -v
(press Ctrl + c)
.......... 
$ pgrep nntrainer
11960
```

**Comment by kparichay** [comment]
> this should be handled with databuffer refactoring.

Please move/link this issue to data buffer refactoring issue.

**Comment by kparichay** [comment]
Also, please some logs and specify unittest/apptest to reproduce this.

**Comment by zhoonit** [comment]
> Also, please some logs and specify unittest/apptest to reproduce this.

updated

**Comment by zhoonit** [comment]
It seems like it is issue in meson. https://github.com/mesonbuild/meson/issues/3348, closing
