### ISSUE TITLE
Add architectural support to change backend easily

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#134]
### As-Is
`USE_BLAS` and `USE_CUBLAS` is used to switch tensor operation.

```cpp
Tensor::do_the_math(...) {
#ifdef USE_BLAS
/** implementation **/
#else 
/** implementation **/
#endif
}
```

### To-Be
Switch Tensor Implementation strategically at compile time.

**Comment by myungjoo** [comment]
Another thing you need to consider: performance.

**Comment by zhoonit** [comment]
looks duplicated of #332, plus this should be delayed
