### ISSUE TITLE
weight initializer is fitted for fc layer

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#1352]
weight initializer is not fitted for conv layer, does using ill-formed distribution.

**Comment by kparichay** [comment]
Is the issue for fc layer or conv layer?
Also, can you elaborate more on the issue with the initializer?

**Comment by zhoonit** [comment]
Xavier, Lecun, He initializer assumes that the distribution is determined by the node it is affected by + node it is affecting. 
So, using height and width to calculate those is valid only for fully connected layer case.

Please see https://github.com/nnstreamer/nntrainer/pull/1353

**Comment by zhoonit** [comment]
Closing as the issue has been resolved
