### ISSUE TITLE
RFC: Change input_layers behavior

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#1373]
I think below changes will be necessary for Early Exit, possibly KNN layer. Please review.

# As-is

- `input_layers=foo,bar` 🍥  are intended to create a concat layer (for non concat, non addition layer)
- And then, two inputs become one inputs for all generic layers, there is no way to add a generic layer with two inputs without touching `network_graph`
- This is because we are assuming every layer is getting single input except for the special layers 🐳 

# To-be

- support a generic layer with multiple inputs
- naturally, we don't realize 🍥 to concat or addition layer
- We let layer throw at finalize, if given `initContext` has more inputs then required. (So, it is layer's responsibility to check if given number is correct, we can provide some helperfunctions inside `initContext`)

**Comment by kparichay** [comment]
In the to-be scenario, is it assumed that the given inputs will always be concatenated by the outer dimension?
Usually, the data is concatenated by the inner dimensions.

I like the idea that a generic layer must support multiple inputs but this means that each layer's implementation must be updated to support multiple inputs.

**Comment by zhoonit** [comment]
> In the to-be scenario, is it assumed that the given inputs will always be concatenated by the outer dimension?

If outer dimension means 1D list, you are correct. So there won't be such a concatenation, so we don't need to care about contiguous memory as it is not a single tensor.

This does not mean we support multiple inputs for the all the layers, but the all layers should be recommended to check if given input numbers are matching with the layers requirement at `finalize()`. This change is relatively simple I guess.

**Comment by kparichay** [comment]
I guess we will have to evaluate which layers do support it and somehow get that information when finalizing the graph, as the graph needs to decide at that time if an extra layer has to be added to compensate for a layer not supporting/supporting multiple inputs.

**Comment by zhoonit** [comment]
I think it'd better be a responsibility of a layer to validate, for example, keras does https://stackoverflow.com/a/56167762

**Comment by kparichay** [comment]
> I think it'd better be a responsibility of a layer to validate, for example, keras does https://stackoverflow.com/a/56167762

Yes, the layer would have to validate on its own, but the Graph class needs to make the decision when finalizing the graph if this layer needs support with concat or this layer can handle it on its own?

**Comment by zhoonit** [comment]
I think layer should handle it's own or otherwise error, I think it will be not intuitive we predict what user wants by adding concat or addtion

**Comment by kparichay** [comment]
In that case, we are encouraging layer writers to do the concat/addition operation in their own implementation. Then, concat and addition must be supported with full support as tensor operations, and most of the layers must be updated to handle multiple inputs.
IMO this creates an additional burden for the layer writer, but will be more optimized :) than graph adding Concat layers everywhere.

**Comment by zhoonit** [comment]
This has been done, closing :)
