### ISSUE TITLE
conv/bn model test might be wrong

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#1378]
in the unittest_models, there is conv/bn newly added #1349 
@lhs8928 reported that it is not working when built from a python file.

**Comment by zhoonit** [comment]
In my machine the issue is to be false positive.

Please reopen, if someone else find issue regarding this

**Comment by kparichay** [comment]
@lhs8928: as you reported that it's not working, please reconfirm this.

**Comment by lhs8928** [comment]
This issue is happened with tf version 2.4.0 but with 1.15.4 works fine
