### ISSUE TITLE
Skipping partially filled batch for validation data

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nntrainer#1457]
The current implementation of the data buffer skips the last batch of the data if it is partially filled.
This results in different validation accuracies if validation is run multiple times with shuffling enabled. Some possible solutions are:
1. Support running of partially filled batch (the memory will be the same but the tensor shape will be of smaller batch size). IMO this should pretty much directly work as this is coherent with a Tensor generated with Tensor::Map/SharedDataTensor and we use this everywhere.
2. Throw when batch size doesn't divide the total number of validation data points perfectly.
3. Automatically choose the largest batch size less than the batch size given by the user which divides the total dataset perfectly.

**Comment by kparichay** [comment]
I think this should be fixed with the dataset v2.

**Comment by zhoonit** [comment]
This is resolved dataset v2. Now it is being fed to the neuralnet, and neuralnet has change to decide whether to skip this or not.
