### ISSUE TITLE
Q. Shouldn't CalcGradient be skipped when non-trainable?

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#1598]
https://github.com/nnstreamer/nntrainer/blob/51a871bd7b6e63ddcac6185e55ae802c804d1d70/nntrainer/models/neuralnet.cpp#L244-L245

Current upstream code does not skip calcGradient when `node->trainable() == false`, I wonder if this is because some calculation is depending on calcGradient() (which they shouldn't)?

**Comment by kparichay** [comment]
#1590 covers it - https://github.com/nnstreamer/nntrainer/pull/1590/files#diff-596baff7d3bfcab9105e5feba23efaedfec25215a1231fd5741dcd6c220307bbR484-R485

**Comment by zhoonit** [comment]
Cool. Thanks
