### ISSUE TITLE
Dataset unittest fails

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nntrainer#1604]
dataset unittest was manually setting the batch size to 1 where the inputs and labels were set with batchsize 20. 
#1544 removes the setting the batchsize of 1 to pass `error_once_or_not_pn/0` but `fetch_one_epoch_or_10_iteration_pn` still fails.

**Comment by zhoonit** [comment]
I think this is not bug, producer is supposed to give only a single sample at a time. You can disable it I'll look into it.

**Comment by zhoonit** [comment]
Please refer to #1605
