### ISSUE TITLE
ENABLE_TEST=false does not work

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#1664]
ENABLE_TEST=false does not work on some models. 

Error is requesting gradient for non trainable tensors.

I think if there is a intermediat non trainable tensor, it seems affecting it.

**Comment by kparichay** [comment]
Can you please expand which models fail? below works for me on the latest main branch:
```
meson build -Denable-test=false
cd build
ninja test
```

Note that the MNIST unit test is supposed to timeout as it tries to run for 1500 epochs (compared to 5 epochs with ENABLE_TEST).

**Comment by zhoonit** [comment]
> Can you share the model failing log here? below works for me on the latest main branch:
> 
> ```
> meson build -Denable-test=false
> cd build
> ninja test
> ```
> 
> Note that the MNIST unit test is supposed to timeout as it tries to run for 1500 epochs (compared to 5 epochs with ENABLE_TEST).

Could you install and try run tacotron? I tried in android devices and was failing.

**Comment by kparichay** [comment]
Yes, tacotron fails with main branch with ENABLE_TEST=false, but passes with #1687 :)

**Comment by zhoonit** [comment]
Awesome :) could you make this close when #1687 merges?

**Comment by kparichay** [comment]
Added.
