### ISSUE TITLE
Recurrent realizer stuck in loop with SliceRealizer

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nntrainer#1705]
Recurrent realizer gets stuck in a loop with slice realizer while trying to work with start and end layers.
There should be checks in the realizer to avoid this scenario.

**Comment by zhoonit** [comment]
Could you specify a scenario for repro? If you are already working on this, I'll check the test inside PR instead :)

**Comment by kparichay** [comment]
I am working on this, there a few bugs in SliceRealizer and will fix them all at once.

**Comment by zhoonit** [comment]
pk could you check if the issue has been resolved?

**Comment by kparichay** [comment]
This is resolved.
