### ISSUE TITLE
Embedding padding concept

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nntrainer#1729]
Embedding layer introduces the concept of padding where the input index 0 is reserved for not filling the output. I have two doubts:
1. If filling the output is skipped, this results in uninitialized values. Is this intended?
2. Currently 0 is always assumed to be not filling the output but should be enabled/disabled with boolean. Further, this padding_idx should be allowed to be set as a property.

**Comment by jijoongmoon** [comment]
actually if the data is 0, then I guess it need throw error if it is not controlled with option as you mentioned 2. current implementation always has to be start with 1.

**Comment by kparichay** [comment]
We will have a property `pad_idx` which if set will determine what is the padding index and if the padding is enabled or not.
If the `pad_idx` is set, then the weights for that idx will be reset to 0.
