### ISSUE TITLE
Model c++ api

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#1789]
It's about time to open/fixate model C++ API.

We need list of things which should be supported.

### 1. Modification
- list to be added

### 2. Enhancement
- some callbacks to entries

**Comment by myungjoo** [comment]
If you have a class diagram of C++ APIs, @again4you may be able to review it.

**Comment by kparichay** [comment]
> If you have a class diagram of C++ APIs, @again4you may be able to review it.

@jijoongmoon can you check. I think this might be helpful for the ATC paper as well.
