### ISSUE TITLE
Teacher forcing support

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#1816]
number of things to enable teacher forcing for the recurrent wrapper

- Add Identity Layer #1795
- Enable multiout with dangling #1798
- Enable multiout with dangling with optimized mode #1818
- Recurrent realizer support connections #1799
- lstm cell and zone out lstm cell support connection #1815
- as_sequence support connection #1802
- multi inout for lstmcell, zoneout lstmcell #1817

**Comment by kparichay** [comment]
@zhoonit Please close if this is done.

**Comment by zhoonit** [comment]
There are some (design) improvisers in the above PR's but I guess it's okay to close for now.
