### ISSUE TITLE
Deep memory copy between layers

### ISSUE THREAD

**Issue by jijoongmoon** [nnstreamer/nntrainer#184]
currently, there is deep memory copy between layers. We have to resolve this.

**Comment by zhoonit** [comment]
I think change signature 
`Tensor forwarding(Tensor in, int &status);`  -> `Tensor forwarding(const Tensor &in, int &status;)` (and for backwarding) would resolve the problem to some extent.

Would that be applicable?

**Comment by kparichay** [comment]
> I think change signature
> `Tensor forwarding(Tensor in, int &status);` -> `Tensor forwarding(const Tensor &in, int &status;)` (and for backwarding) would resolve the problem to some extent.
> 
> Would that be applicable?

I like it. It is needed especially for the layers where forwarding can be in place (if possible).

**Comment by kparichay** [comment]
@jijoongmoon Please check and close this (IMO this is done).
