### ISSUE TITLE
Adding copy and move constructor for tensor

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nntrainer#185]
In my understanding, `class tensor` does not has an explicitly written copy constructor. This leads to the use of the default copy constructor for itself and its elements. The default copy constructor for a `std::vector<>` copies all the elements inside the vector. As `std::vector<float> data` in `tensor` exists, a new vector is created and copied with each copy constructor use.

The repository code uses the copy constructor with `tensor` at many places (with direct uses such as `Tensor x = y`). This leads to unintentional data copy.

The same applies to move constructor.

**Comment by jijoongmoon** [comment]
Right. I agreed.

**Comment by zhoonit** [comment]
I am gonna be making copy assignment operator and move assignment operator

**Comment by kparichay** [comment]
> I am gonna be making copy assignment operator and move assignment operator

If we have shared_ptr, IMO we do not need to write the copy and move assignment operator again.
@zhoonit close this once shared_ptr PR merges.

**Comment by kparichay** [comment]
> I am gonna be making copy assignment operator and move assignment operator

If we have shared_ptr, IMO we do not need to write the copy and move assignment operator again.
@zhoonit close this once shared_ptr PR merges.

**Comment by zhoonit** [comment]
I think we need a consensus on this topic.

You know in python family tensor library, `shared_ptr` kind of implementation is used. for example in numpy:

```python
>> import numpy as np
>> 
>> a = np.arange(5)
>> b = a
>> b[2] = -1
>> print(a)
array([ 0,  1, -1,  3,  4])
```

If you want to copy, you need to explicitly call copy like...

```python
>> import numpy as np
>> 
>> a = np.arange(5)
>> b = a.copy()
>> b[2] = -1
>> print(a)
array([ 0,  1, 2,  3,  4])
```

However, in c++ we have `reference operator` and `move assignment operator` in c++ which can do such job 

for example

```cpp
>> Tensor a = {1, 2, 3, 4, 5} // just an illustration.
>> Tensor &b = a;
>> b.getData()[2] = -1

>> std::cout << a;
1, 2, -1, 4, 5
```
or if you need to change the scope of a certain Tensor....
```cpp
>> Tensor a = {1, 2, 3, 4, 5}
>> Tensor b = std::move(a);
>> b.getData()[2] = -1;
```
Which python can't do.


So I think it is more natural to use copy assignment operator to copy the inner data structure as well (or use flag sth like copy-on-write?)




Another concern is that changing the semantics of copy operator as noted

**Comment by kparichay** [comment]
> So I think it is more natural to use copy assignment operator to copy the inner data structure as well. (would be even better if we use flag sth like copy-on-write and check before *_i() operation happens?)

IMO, using these semantics is confusing as the major constituent of the tensor is a `shared_ptr`. I think the copy/move constructor/assignment operators should follow the semantics of the `shared_ptr` itself.
Further, if we are going to create a copy of the internal data structure with copy assigment, then IMO, there is no major advantage with using shared_ptr compared with directly vector. 

> Another concern is that changing the semantics of copy to not copy inner data changes the interface. Then we need to check every code other than tensor as @kparichay noted #235.

Yes, it will change the interface. However, this removes all the unnecessary memory copies in the code.

I think @jijoongmoon @myungjoo @wooksong @dongju-chae can provide some comments on which way is more appropriate.

**Comment by kparichay** [comment]
After the discussion with @wooksong, let's convert `std::vector<T>` to `std::shared_ptr<T *>`, where the memory allocation will be done manually for the `T *`. `tensor.cpp` does not heavily rely on `std::vector<>` functionalities, but the overhead of vector and memory management of `std::vector<>` creates issues for expansion of `tensor` for other backends and merging with nnfw.

**Comment by zhoonit** [comment]
I guess this can now be closed if @kparichay  is okay.

We need to fix the copy constructor but not directly related to this issue.

**Comment by kparichay** [comment]
Let's close this and make a new issue for `fix memcopy in copy constructor `
