### ISSUE TITLE
Running Logistic Regression on Android

### ISSUE THREAD

**Issue by udit01** [nnstreamer/nntrainer#1908]
I was running an example model using the instructions here: https://github.com/nnstreamer/nntrainer/blob/main/docs/how-to-run-example-android.md

I am running the application on device: Note 10 with android 10.

After building the application with ndk-build, the output is 4 files, `libc++_shared.so libccapi-nntrainer.so libnntrainer.so nntrainer_logistic ` in the `libs/arm64_v8a` folder . 

Using adb push to transfer those and the 3 resource files into /data/local/tmp on device

```bash
d1x:/data/local/tmp $ ls                                                                                                                  
LogisticRegression.ini dataset1.txt libc++_shared.so libccapi-nntrainer.so libnntrainer.so  logistic_model.bin nntrainer_logistic test.txt 

```

After executing:
```bash
d1x:/data/local/tmp $ ./nntrainer_logistic                                                                                                                               
CANNOT LINK EXECUTABLE "./nntrainer_logistic": library "libomp.so" not found
```
I temporarily fixed these by copying the libopm.so for ARM64 from ndk folder to the device.

```bash
adb push /home/udit/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/12.0.8/lib/linux/aarch64/libomp.so /data/local/tmp/
```

Then the training is working using : ` $  ./nntrainer_logistic train LogisticRegression.ini  dataset1.txt     `

But the testing/inference is NOT working

```bash
|d1x:/data/local/tmp $ ./nntrainer_logistic inference LogisticRegression.ini   test.txt                                                                                 
WARNING: linker: Warning: "/data/local/tmp/libc++_shared.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)
WARNING: linker: Warning: "/data/local/tmp/libc++_shared.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)
WARNING: linker: Warning: "/data/local/tmp/libc++_shared.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)
Error during forwarding the model
```

Could you please look into why exactly is the inference failing?

And is manually copying the dynamically linked libomp.so needed or is there a better fix to the issue?

@myungjoo @jijoongmoon

**Comment by jijoongmoon** [comment]
Thanks for the issue! You can test with #1910

**Comment by udit01** [comment]
Thanks for the quick response! I'll test it out, let you know and close the issue tommorow.

**Comment by udit01** [comment]
Tested on device.
Both Training and Inference work.
Using ./tools/package_android.sh and then using the updated packaged libraries doesn't throw the libomp missing error too.
Thanks for the fix!
