### ISSUE TITLE
Support n-dim input in fc layer

### ISSUE THREAD

**Issue by lhs8928** [nnstreamer/nntrainer#1924]
For now, fc layer support 2-dim input(batch, 1, 1, width).
NNTrainer needs to support n-dim input in fc layer.

This might be helpful. (https://numpy.org/doc/stable/reference/generated/numpy.matmul.html)
According to the description

> If either argument is N-D, N > 2, it is treated as a stack of matrices residing in the last two indexes and broadcast accordingly.

**Comment by jijoongmoon** [comment]
This is done with https://github.com/nnstreamer/nntrainer/pull/1927.
