### ISSUE TITLE
Merge DataLoader in Application in Application Utils.

### ISSUE THREAD

**Issue by jijoongmoon** [nnstreamer/nntrainer#1969]
Currently, ResNet Style DataLoader is used quite a lot and It needs to be merged and shared as an util function in utils directory.

**Comment by DonghakPark** [comment]
NNtrainer {Resnet, AlexNet, VGG} use CifarDataLoader so I will merge them into util function

**Comment by lhs8928** [comment]
Just mention in your commit to close this issue using keywords (please refer https://docs.devart.com/studio-for-sql-server/source-controlling-databases/associating-commits-with-github-issues.html)

**Comment by DonghakPark** [comment]
Close this issue after merge #1967
