### ISSUE TITLE
Upgrade Tensorflow lite to 1.14.0

### ISSUE THREAD

**Issue by jijoongmoon** [nnstreamer/nntrainer#20]
Currently we are using tensorflow lite 1.9.0. Should upgrade 1.14.0.

**Comment by myungjoo** [comment]
Nah...let's move to 1.13.1. It's going to be the standard for both Android/Tizen products for a while.
Anyway keeping it compatible with multiple versions of tf-lite is good (as nnstreamer.git does now: 1.9 ~ 1.15).

**Comment by jijoongmoon** [comment]
Done with #208
