### ISSUE TITLE
Make a tensor equal operation

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#202]
`Tensor` is lack of comparison operation which make it hard to test.

It would be better to have tensor `==` operator overloaded.

**Comment by kparichay** [comment]
I have created a basic PR with fixed epsilon #
TODO: update based on bit changes in mantissa as done in gtest.

**Comment by kparichay** [comment]
TODO: update based on bit changes in mantissa as done in gtest.

**Comment by kparichay** [comment]
Closing for now.
If the current operation becomes a limitation, this can be reopened.
