### ISSUE TITLE
Doubt regarding libc++_shared on the nntrainer build

### ISSUE THREAD

**Issue by adjhawar** [nnstreamer/nntrainer#2042]
1. What is the use of libc++_shared.so in the daily builds of nntrainer? 
2. How is that supposed to be included in the project?

My application is using nntrainer on android. I have included the nntrainer and ccapi-nntrainer libs in my project but the libc++_shared library included in the application is causing it to crash.

**Comment by myungjoo** [comment]
What is your build environment and configuration? Are you writing your own build scripts or tools?

libc++_shared.so is included in Android NDK releases.
Is this related?: https://stackoverflow.com/questions/28504875/android-ndk-cannot-load-libc-shared-so-gets-cannot-locate-symbol-rand-refe

**Comment by adjhawar** [comment]
The environment is Android. I am just linking the prebuilt nntrainer shared libraries with my project. 
The build was successful but while running the nntrainer APIs, the application crashes.

**Comment by jijoongmoon** [comment]
Could you try buile the nntrainer library from sources? The procedure is pretty straight forward and the details are https://github.com/nnstreamer/nntrainer/blob/main/docs/how-to-run-example-android.md
