### ISSUE TITLE
[CAPI] request ml_train_layer_get_weight(ml_train_layer_h *layer, const char *layer_name, float** weights, int** weight_dims)

### ISSUE THREAD

**Issue by jijoongmoon** [nnstreamer/nntrainer#2045]
There is a request to support get Weight for specific layer as an C API. 
So far, NNTrainer has ml_train_model_get_layer(). 

We also can support the model API such as.

```C
 ml_train_model_get_weight(const char* layer_name, float** weights, int** weight_dims) 
```

also, layer API 

```C
ml_train_layer_get_layer(ml_train_model_h model, const char *layer_name, ml_train_layer_h *layer);
ml_train_layer_get_weight(ml_train_layer_h *layer, float** weights, int** weight_dims);
```

**Comment by daeinki** [comment]
I wonder what each parameter of ml_train_layer_get_weight function means.

float** weights : weight values with multiple dims to a given layer.
int** weight_dims : dim info of each weight.

I'm not sure I catched it up on this correctly but If ok then, how we can know how much objects weights and weight_dims have?
Shouldn't we need weight_size which means how much objects each parameter has?

**Comment by daeinki** [comment]
> I wonder what each parameter of ml_train_layer_get_weight function means.
> 
> float** weights : weight values with multiple dims to a given layer. int** weight_dims : dim info of each weight.
> 
> I'm not sure I catched it up on this correctly but If ok then, how we can know how much objects weights and weight_dims have? Shouldn't we need weight_size which means how much objects each parameter has?

I think .getWeights().size() is what we need in addition.

**Comment by jijoongmoon** [comment]
Let's assume, Fully Connected Layer, the number of weight is two (for, W and Bias), the dimension will be, (1, 1, H, W), (1,1,1, W) for each of them. 
when developer call the ml_train_model_get_weight( const char * layer_name, float ** weights,  int** weight_dim), then 
he will get, 
float weights[0] will be for the W, weights[1] will be for the bias. and the weigth_dim[0] includes 4 integer number which is [ 1,1,H,W ] and weight_dim[1] will be [1,1,1, w].

**Comment by daeinki** [comment]
> Let's assume, Fully Connected Layer, the number of weight is two (for, W and Bias), the dimension will be, (1, 1, H, W), (1,1,1, W) for each of them. when developer call the ml_train_model_get_weight( const char * layer_name, float ** weights, int** weight_dim), then he will get, float weights[0] will be for the W, weights[1] will be for the bias. and the weight_dim[0] includes 4 integer number which is [ 1,1,H,W ] and weight_dim[1] will be [1,1,1, w].

Understood.The length of weights and weight_dims are fixed with 2. This was why .getWeights().size() always returns 2. Thanks for explanation. :)

**Comment by daeinki** [comment]
> 

BTW, wouldn't we need to notify the length to user? Without the length value, this would mean that weights has weight and bias values implicitly. So user has to know that the length is 2 in advance. How about notifying it to user explicitly? Just my opinion. :)

**Comment by daeinki** [comment]
> ```c
> ml_train_layer_get_weight(ml_train_layer_h *layer, float** weights, int** weight_dims);
> ```

Or, introducing explicit APIs may be good idea like below,
ml_train_layer_get_weight(ml_train_layer_h *layer, float** weights, int** weight_dims);
ml_train_layer_get_bias(ml_train_layer_h *layer, float** bias, int** bias_dims);

**Comment by myungjoo** [comment]
> There is a request to support get Weight for specific layer as an C API. So far, NNTrainer has ml_train_model_get_layer().
> 
> We also can support the model API such as.
> 
> ```c
>  ml_train_model_get_weight(const char* layer_name, float** weights, int** weight_dims) 
> ```
> 
> also, layer API
> 
> ```c
> ml_train_layer_get_layer(ml_train_model_h model, const char *layer_name, ml_train_layer_h *layer);
> ml_train_layer_get_weight(ml_train_layer_h *layer, float** weights, int** weight_dims);
> ```

==>

```c
ml_train_layer_get_layer(ml_train_model_h model, const char *layer_name, ml_train_layer_h *layer);
ml_train_layer_get_weight(ml_train_layer_h layer, float** weights, int** weight_dims);
```

and maybe.. get_layer, get_weight or...

```c
ml_train_layer_get_weight(ml_train_layer_h layer, float** weights, int** weight_dims, float **bias, int **bias_dims);
```
and weights and bias are NULLABLE (if NULL, it is not retrieved.)

**Comment by jijoongmoon** [comment]
Right. there is no need for the ```*``` for the get_weight. And I'm not sure we need to separate the bias though for the consistency for all layers.

**Comment by daeinki** [comment]
> > There is a request to support get Weight for specific layer as an C API. So far, NNTrainer has ml_train_model_get_layer().
> > We also can support the model API such as.
> > ```c
> >  ml_train_model_get_weight(const char* layer_name, float** weights, int** weight_dims) 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > also, layer API
> > ```c
> > ml_train_layer_get_layer(ml_train_model_h model, const char *layer_name, ml_train_layer_h *layer);
> > ml_train_layer_get_weight(ml_train_layer_h *layer, float** weights, int** weight_dims);
> > ```
> 
> ==> (no `*` for `ml_train_layer_h`) in get_weight)

Right. just ml_train_layer_h not *. It's my mistake. :)

```
ml_train_layer_get_weight(ml_train_layer_h layer, float** weights, int** weight_dims);
```

> 
> ```c
> ml_train_layer_get_layer(ml_train_model_h model, const char *layer_name, ml_train_layer_h *layer);
> ml_train_layer_get_weight(ml_train_layer_h layer, float** weights, int** weight_dims);
> ```
> 
> and maybe.. get_layer, get_weight or...
> 
> ```c
> ml_train_layer_get_weight(ml_train_layer_h layer, float** weights, int** weight_dims, float **bias, int **bias_dims);
> ```
> 
> and weights and bias are NULLABLE (if NULL, it is not retrieved.)

**Comment by daeinki** [comment]
> > There is a request to support get Weight for specific layer as an C API. So far, NNTrainer has ml_train_model_get_layer().
> > We also can support the model API such as.
> > ```c
> >  ml_train_model_get_weight(const char* layer_name, float** weights, int** weight_dims) 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > also, layer API
> > ```c
> > ml_train_layer_get_layer(ml_train_model_h model, const char *layer_name, ml_train_layer_h *layer);
> > ml_train_layer_get_weight(ml_train_layer_h *layer, float** weights, int** weight_dims);
> > ```
> 
> ==> (no `*` for `ml_train_layer_h`) in get_weight)
> 
> ```c
> ml_train_layer_get_layer(ml_train_model_h model, const char *layer_name, ml_train_layer_h *layer);
> ml_train_layer_get_weight(ml_train_layer_h layer, float** weights, int** weight_dims);
> ```
> 
> and maybe.. get_layer, get_weight or...
> 
> ```c
> ml_train_layer_get_weight(ml_train_layer_h layer, float** weights, int** weight_dims, float **bias, int **bias_dims);
> ```

Yeah, we could drop the implicit thing by providing specified parameters, weights and bias. :)

> 
> and weights and bias are NULLABLE (if NULL, it is not retrieved.)
