### ISSUE TITLE
[lstm] Update LSTMLayer so as to support Keras  'return_state' functionality

### ISSUE THREAD

**Issue by alexzami** [nnstreamer/nntrainer#2046]
Hi,
I am trying to modify the LSTMLayer in order to support the functionality of the return_state=True of Keras LSTM layer. Thus, I need to return 3 tensors as the output of the layer.

In the LSTMLayer in the finalize function, I have set the number of output dimension as three (3).

```
const TensorDim output_dim(batch_size, 1, return_sequences ? max_timestep : 1,
                             bidirectional ? 2 * unit : unit);
const TensorDim output_hidden_state_dim(batch_size, 1, 1,
                             bidirectional ? 2 * unit : unit);
const TensorDim output_cell_state_dim(batch_size, 1, 1,
                             bidirectional ? 2 * unit : unit);
context.setOutputDimensions({output_dim, output_hidden_state_dim, output_cell_state_dim});
```

In the forwarding function, I get the three output tensors as follows:

```
static constexpr size_t RETURN_STATE_OUT_IDX = 0;
static constexpr size_t RETURN_STATE_HIDDEN_IDX = 1;
static constexpr size_t RETURN_STATE_CELL_IDX = 2;

Tensor &output = context.getOutput(RETURN_STATE_OUT_IDX);
Tensor &output_hidden = context.getOutput(RETURN_STATE_HIDDEN_IDX);
Tensor &output_cell = context.getOutput(RETURN_STATE_CELL_IDX);
```

And then I fill in the tensors accordingly.

My problem is that, while in the LSTMLayer::forwarding when we print out the dimension of the output we get the expected size (3) , when we call the inference of the graph having as its last layer the LSTMLayer, then the number of the returned output tensors is 1.

For example:

I define the following graph:

```
  std::shared_ptr<ml::train::Layer> input_layer = ml::train::layer::Input({"input_shape=1:1:1:320", "trainable=false", "name=input0"});
  std::shared_ptr<ml::train::Layer> lstm_layer  = ml::train::layer::LSTM({
                    "name=conformer_prediction_lstm_0",
                    "unit= 320", "activation=tanh", "return_sequences=true",
                    "recurrent_activation=sigmoid", "integrate_bias=true", 
                    "input_layers=input0", "trainable=false"
  });  

predict_net = ml::train::createModel(ml::train::ModelType::NEURAL_NET);

predict_net_NN.addLayer(input_layer);
predict_net_NN.addLayer(lstm_layer);

predict_net_NN.compile();
predict_net_NN.initialize();
```
When I try to call the inference:

```
nntrainer::Tensor predicted_tensor(nntrainer::TensorDim(1,1,1,320));
predicted_tensor.setZero();
auto out = predict_net_NN.inference({MAKE_SHARED_TENSOR(predicted_tensor)});
```
the size of out is of dimension=1

Is this the expected dimension for the output? I was thinking that it should be 3.

Can you please advise me?
Thank you in advance

**Comment by lhs8928** [comment]
Hi alexzami.
Sorry for late reply.
That's because the key string of hidden state activation property for lstm is "hidden_state_activation" not "activation".
So if you modify lstm layer as

```
  std::shared_ptr<ml::train::Layer> lstm_layer  = ml::train::layer::LSTM({
                    "name=conformer_prediction_lstm_0",
                    "unit= 320", "hidden_state_activation=tanh", "return_sequences=true",
                    "recurrent_activation=sigmoid", "integrate_bias=true", 
                    "input_layers=input0", "trainable=false"
  });  
```
it will return output size of 3.

FYI activation property means that lstm layer needs following activation layer so that's why the output is 1.

If you have any further problem please leave it in issues :)

**Comment by alexzami** [comment]
Thank you for the quick reply. that solves the issue :)

**Comment by lhs8928** [comment]
Can I close this issue if there is no other problems?

**Comment by alexzami** [comment]
One minor comment 
I tried to pass a second input to the LSTM layer, in order to initialize the cell state and to implement the "initial_state" function of Keras
in this case, I noticed that the output size is 4 instead of 3 
not a big problem for me. I post this as an observation
