### ISSUE TITLE
Different output between NNTrainer and Tensorflow models after weights initialization

### ISSUE THREAD

**Issue by alexzami** [nnstreamer/nntrainer#2062]
Hello all, 
I am trying to create a simple test model in order to test the loading of weights from the Tensorflow model to NNtrainer. I do the following steps:

1. I create a model with only one Embedding layer (both on NNTrainer and Tensorflow)  
Tensorflow definition
```
self.embed = Embedding(1031, 320, regularizer=tf.keras.regularizers.l2(1e-6))
```
NNTrainer definition
```std::shared_ptr<ml::train::Layer> input_layer_test = ml::train::layer::Input({"input_shape=1:1:1:1", "trainable=false", "name=input0t"});

std::shared_ptr<ml::train::Layer> embedding_layer_test = ml::train::layer::Embedding({
                    "in_dim=1031", "out_dim=320", "name=conformer_prediction_embedding_test", 
                    "input_layers=input0t", "trainable=false", "weight_initializer=lecun_uniform", 
                    "weight_regularizer=l2norm"});
                    
predict_net_NN_test.addLayer(input_layer_test);
predict_net_NN_test.addLayer(embedding_layer_test);
predict_net_NN_test.compile();
predict_net_NN_test.initialize();
```
2. then I save the weights from Tensorflow model 
```
emb_0 = np.transpose(self.embed.get_weights()[0])
save("predict_net.bin", emb_0)
```
  where save is defined as follows (based on the existing examples on the NNTrainer repo)
``` 
import numpy as np
def save(filename, *data):
    with open(filename, 'ab+') as outfile:
        for item in data:
          np.array(item, dtype=np.float32).tofile(outfile)
          try:
            print(item.shape, " data is generated")
          except:
            pass
```
3. try loading them to the NNTrainer model
`predict_net_NN_test.load("predict_net.bin", ml::train::ModelFormat::MODEL_FORMAT_BIN);`
4. run inference on both models to check the output
``` 
nntrainer::Tensor t1(nntrainer::TensorDim(1,1,1,1));
t1.setZero();
auto out_test = predict_net_NN_test.inference({MAKE_SHARED_TENSOR(t1)});
```

I also check that the loaded weights are the same using the following code:
```
std::shared_ptr<ml::train::Layer> enc_0, dec_0, add, tanh, vocab_0;
predict_net_NN_test.getLayer("conformer_prediction_embedding_test", &enc_0);  
std::vector<float *> layer_w_e = enc_0->getWeights();
```

The problem is that the outputs are not only different but the values of the output on the NNTrainer seem extreme (some of the are quite big and some of them are quite low, e.g. 1.5e+41)

Do I save and load the weights in the proper way?

Please advise us on the aforementioned problems.
Thank you in advance

**Comment by baek2sm** [comment]
Thank you for writing the issue in detail. Based on what you said, I will verify the relevant part and give you an answer again!

**Comment by baek2sm** [comment]
In order to obtain results such as Tensorflow, the following two modifications must be reflected in your code.

1. Save the weights of tensorflow without using the transpose function.
`emb_0 = model.get_weights()[0]`

2. When calling inference function, set the 'free_mem' option to false as follows.
`predict_net_NN_test.inference({MAKE_SHARED_TENSOR(t1)}, false);`

Reflecting these modifications will give you the desired results. Thanks.

**Comment by alexzami** [comment]
Hi @baek2sm,
Indeed! I applied the suggested modification and I got the desired results.

Thank you very much :)
