### ISSUE TITLE
Issue with bmp processing during ResNet application inference

### ISSUE THREAD

**Issue by KirillP2323** [nnstreamer/nntrainer#2207]
Hello, I'm using the ResnetJNI application as a template to build android APK.
I'm working on implementing the `Infer` function in the app, and I'm using `inferModel` from https://github.com/nnstreamer/nntrainer/blob/main/Applications/Android/ResnetJNI/app/src/main/jni/resnet.cpp#L565 
However, it looks like the `input` variable is constant across different images I tried. Adding this snippet
```
  for (unsigned int i = 0; i < 5; i++) {
    ANDROID_LOG_I("%s", std::to_string(input[i].c_str());
  }
```
[here](https://github.com/nnstreamer/nntrainer/blob/main/Applications/Android/ResnetJNI/app/src/main/jni/resnet.cpp#L604) always outputs these numbers:
```
-0.000000
1.000000
2.000000
3.000000
4.000000
```
I think the issue might be because of pBmp processing here: https://github.com/nnstreamer/nntrainer/blob/main/Applications/Android/ResnetJNI/app/src/main/jni/resnet_jni.cpp#L134

**Comment by myungjoo** [comment]
> I think the issue might be because of pBmp processing here: https://github.com/nnstreamer/nntrainer/blob/main/Applications/Android/ResnetJNI/app/src/main/jni/resnet_jni.cpp#L134

Could you please elaborate?

**Comment by KirillP2323** [comment]
I'm not completely sure how the process works, but it looks to me like on https://github.com/nnstreamer/nntrainer/blob/main/Applications/Android/ResnetJNI/app/src/main/jni/resnet_jni.cpp#L134 we assign RGB values of `(i,j,0)` to pixel `(i,j)` of `pBmp`, instead of copying information from `bmp` object.

**Comment by jijoongmoon** [comment]
We will check. Thanks for the issues.
