### ISSUE TITLE
Unittest accuracy has turned bad

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nntrainer#221]
Unittest accuracy of `nntrainer_capi_nnmodel.train_with_generator_01_p` has turned bad from over 40% to under 20%.

**Comment by kparichay** [comment]
@zhoonit @jijoongmoon How about first add fixed values to accuracy and loss which are tested in the unit test rather than just checking if the code runs or not, before merging further PRs?

**Comment by zhoonit** [comment]
Sounds good idea!
