### ISSUE TITLE
Tizen-native Custom short crashing on 6.0 wearable emulator

### ISSUE THREAD

**Issue by JagratiVerma1408** [nnstreamer/nntrainer#2259]
the application is taking fine output  when click on training after clicking on eval after guess the app  crashing 
with error log :
07-31 17:28:46.933 : Error / CRASH_MANAGER ( 7146 : 7146 ) : crash-manager.c: execute_crash_stack(791) > Read hash error: Resource temporarily unavailable
07-31 17:28:46.933 : Error / CRASH_MANAGER ( 7146 : 7146 ) : crash-manager.c: execute_crash_stack(802) > Unsuspected hash format
07-31 17:28:47.060 : Error / BUXTON ( 7159 : 7159 ) : config.c: load_log_conf(312) > log config log on : True , max line 2000
07-31 17:28:47.066 : Error / BUXTON ( 7160 : 7160 ) : config.c: load_log_conf(312) > log config log on : True , max line 2000

**Comment by myungjoo** [comment]
I don't think anyone can answer anything only with that information.

**Comment by myungjoo** [comment]
@lhs8928 Is this the issue you are looking at? (are you able to reproduce the error?)
