### ISSUE TITLE
[blas/neon] Support various data types for `scopy`

### ISSUE THREAD

**Issue by djeong20** [nnstreamer/nntrainer#2332]
Currently, `scopy` is limited to copying certain data types (float, fp16). Since the tensor data type has been extended to int4 and int8, `scopy` should also support these data types (e.g., `scopy` from int4 to fp32 and int8 to fp16. 

Additionally, `scopy` from int4 to fp16 has been newly implemented and is currently being used. It takes `uint8_t` as a parameter and parses it into two int4 values. However, the problem is that the current `scopy` not only takes int4 but also takes int8 as an input. In other words, it cannot differentiate whether the data is int4 or int8 by a function argument since both use uint8_t.

Therefore, there need to be additional `scopy` functions that support copying int4 and int8 to fp16 and fp32, and the current `scopy` of int4 to fp16 should be revised.

**Comment by skykongkong8** [comment]
Please review #2345 for this issue.

**Comment by skykongkong8** [comment]
#2345 is merged. I think we can close this issue.
@djeong20

**Comment by djeong20** [comment]
Resolved in #2345 and #2357.
