### ISSUE TITLE
Dependency Clean Up Request

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nntrainer#2333]
1. Make the dependency on tensorflow-lite optional (use 'feature' for meson_option)
2. Refactor backend options with 'feature' (for 'auto' mode)

Rationale:

It's quite strange to require tf-lite when you build w/o any meson options.
With 'feature', you can enable tf-lite only if it's installed (no error if tf-lite doesn't exist)
However, for distro builds (Tizen, Ubuntu, ...), we need 'force-enable', which will emit errors if it doesn't exist.

CC: @DonghakPark

**Comment by DonghakPark** [comment]
> 1. Make the dependency on tensorflow-lite optional (use 'feature' for meson_option)
> 2. Refactor backend options with 'feature' (for 'auto' mode)
> 
> Rationale:
> 
> It's quite strange to require tf-lite when you build w/o any meson options. With 'feature', you can enable tf-lite only if it's installed (no error if tf-lite doesn't exist) However, for distro builds (Tizen, Ubuntu, ...), we need 'force-enable', which will emit errors if it doesn't exist.
> 
> CC: @DonghakPark

Okay, i will clean up dependency ASAP

**Comment by myungjoo** [comment]
It's not an ASAP item. We do not have a deadline for this "long-term maintenance". If you have any other pending tasks with deadlines, you should do those first.
