### ISSUE TITLE
Refactor ini file configuration

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nntrainer#239]
ini file has some redundancies as well as ambiguities.
Refactor ini file configuration.

**Comment by kparichay** [comment]
- [ ] Update ini parsing - #240
- [ ] Make ini variables more intuitive
- [ ] Make flatten as a parameter than layer
- [ ] Simplify `neuralnet::init`

**Comment by kparichay** [comment]
Supporting skip connection would look something like this:
```diff
 # Layer Section : Name
 [inputlayer]
 Type = input
 HiddenSize = 128	# Input Layer Dimension
 Activation = sigmoid
 
 [fc1layer]
 Type = fully_connected
 HiddenSize = 20
 Activation = sigmoid
 
 [fc2layer]
+InputLayers = fc1layer                 # Regular connection - redundant
 Type = fully_connected
 HiddenSize = 20
 Activation = sigmoid
 
 [fc3layer]
+InputLayers = fc1layer , fc2layer       # Skip connection with concat operation
 Type = fully_connected
 HiddenSize = 20
 Activation = sigmoid
 
 [outputlayer]
+InputLayers = fc1layer + fc3_layer     # Skip connection with addition operation
 Type = output
 HiddenSize = 3
 Activation = sigmoid
```

Original Network
Input -- fc1 -- fc2 -- fc3 -- Output

New Network with skip connection
```
Input -- fc1 -- fc2 --- =fc3 -- + --Output
             |____ | ___|            |
                       |__________|
```

The intention is to support skip connection with element-wise addition or contact operation intuitively without needing the user to add another layer for this purpose. Internally, this would add `elementwise-add` or `concat` layer depending on the type of skip connection used. 
@jijoongmoon @zhoonit @myungjoo Please make suggestions.

**Comment by myungjoo** [comment]
```
Input -- fc1 -- fc2 --+- fc3 --+- Output
          |___________|        |
          |____________________|
```
?

Looks good to me.

When we allow to use .circle format, we will still need this .ini file to supply training info for "deployed (inference-only) model" to retrain (adjust weights, add layers, ...). We may need a small workshop to share the vision of nntrainer 2021-2022 next week or later (w/ all related members)

**Comment by kparichay** [comment]
Right, my diagram got a bit buggy.
The below will be supported.
```
Input -- fc1 -- fc2 --+- fc3 --+- Output
          |___________|        |
          |____________________|
```

However the example is actually for below:
```
Input -- fc1 -- fc2 -- fc3 --+- Output
          |_____________|    |
          |__________________|
```
Here the input for fc3 (namely fc1 and fc2)  are concatenated, and inputs for output layer (namely fc1 and fc3) are added element wise .

**Comment by zhoonit** [comment]
looks okay to me though the topic is slightly out of my scope
