### ISSUE TITLE
Some confusion about random dataset

### ISSUE THREAD

**Issue by eightreal** [nnstreamer/nntrainer#2525]
Hello, 

I'm looking at your randomDataset code when I'm writing code, but two parts of it look a little strange, and I'm not sure if you did it on purpose or if it's a bug.

This function processing process is a bit strange. Could you help explain it ?

https://github.com/nnstreamer/nntrainer/blob/5fbaf163c26cec26ac3b8df8c1aec4b9df8a09f4/Applications/utils/datagen/cifar/cifar_dataloader.cpp#L31-L39

And Why is the label passed in here? It should be the value of cur_label_tensor passed in my understanding.

https://github.com/nnstreamer/nntrainer/blob/5fbaf163c26cec26ac3b8df8c1aec4b9df8a09f4/Applications/utils/datagen/cifar/cifar_dataloader.cpp#L103

**Comment by eightreal** [comment]
收到，谢谢

**Comment by myungjoo** [comment]
maybe.. we need

33: ```*data = 1.0;```
,
38: ```*(data + label) = 1.0; ```
, and a parameter check, ```label < length```.

and additional doxygen entry or comments.

**Comment by jijoongmoon** [comment]
It is for the different cases to take labels. 
Let's say the class ID is 10 for the truck in CFAR10. 
Then, if the size == 1, the data will be filled with 9 and if it is not it will be [ 0,0,0,0,0,0,0,0,1 ] 

Hope it will help.

**Comment by EunjuYang** [comment]
Dooray! Failure Notice



  
  
    
    
  
  
    
        Failure Notice
    
  
  
    
        
        Your message sent to
          
***@***.***
          has failed to be delivered.
        
        
          Please refer to the below for details.
        
    
  
  
    
      
        
          
            * Recipient : 
***@***.***
          
          
            * Sent time : 
2024-03-29T07:53:07
          
          
            * Subject : 
Re: [nnstreamer/nntrainer] Some confusion about random dataset (Issue #2525)
          
          
            
              
                * Remote host said : 
              
              
                
대외비/기밀 메일은 외부 계정으로 발송이 제한되어 일부 메일 발송 실패(수신자가 전달 설정한 경우 포함)
                
              
            
                      
          
        
      
    
  
  
    
        
          This message was sent from a notification-only address that cannot accept incoming email.
          For more information, please contact           ***@***.***
        
    
  
  
    
        © Dooray!.

**Comment by eightreal** [comment]
> It is for the different cases to take labels. Let's say the class ID is 10 for the truck in CFAR10. Then, if the size == 1, the data will be filled with 9 and if it is not it will be [ 0,0,0,0,0,0,0,0,1 ]
> 
> Hope it will help.

Oh, I can understand the case , thanks for your explian,  but I think it should add a check that. 
```
label < length
```

**Comment by jijoongmoon** [comment]
Yes. you are right.

**Comment by eightreal** [comment]
Okay . thanks for your help,
and how about the second question?

**Comment by jijoongmoon** [comment]
> Okay . thanks for your help, and how about the second question?

yes. it is better to use ```cur_label_tensor```. Thanks!

**Comment by eightreal** [comment]
> > Okay . thanks for your help, and how about the second question?
> 
> yes. it is better to use `cur_label_tensor`. Thanks!

thanks for your help!!!

I also have other problem about nntrainer, I will raise another issue
