### ISSUE TITLE
C API support for editing layers with ini model

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nntrainer#260]
Add API to support models created with ini layers.

- [ ] Assign a name to all the layers in the model
- [ ] setProperty to support setting name for each layer
- [ ] Support get layer by name for C-API
- [ ] Get names of all the layers in the model for C-API
- [ ] Give default names to all the layers in the model 
- [ ] verify that each name is unique when adding a new layer

**Comment by myungjoo** [comment]
Please keep in mind that we will be supporting different model formats (i.e., nnfw-runtime's .circle); the API should be not specific to the current .ini format. In such cases (nntrainer of 2021), we may have this .ini file and API calls to add info required for training not available in the given (exported/inference-only) .circle model.

**Comment by kparichay** [comment]
@myungjoo Yes, the API is being tried to be kept generic.

**Comment by kparichay** [comment]
This all done.
