### ISSUE TITLE
[ Tensor ] more types of Tensors are required.

### ISSUE THREAD

**Issue by EunjuYang** [nnstreamer/nntrainer#2733]
Our awesome TensorV2 has been successfully activated.
As of September 12th, 2024, we support the following types of tensors: 

FloatTensor : **`fp32`**, 
HalfTensor : **`fp16`**, 
CharTensor : **`qint8`**, 
ShortTensor : **`uint16`**.

For further expansion of our on-device training capabilities, we also need to incorporate tensors using unsigned 32 bit integers (**`uint32`**) and unsigned 8 bit integers (**`uint8`**).

**Comment by EunjuYang** [comment]
https://github.com/nnstreamer/nntrainer/pull/2735
Android NDK Build test should be resolved

**Comment by skykongkong8** [comment]
On top of that, I believe we should discuss format of quantization parameters, along with which quantization method are we doing to use.

For example, quantization parameters like `zero point` and `scale factor` are NYI as far as I know.
They might be given as a scalar value, or channel-wise vector, or even row / col - wise vector.

**Comment by EunjuYang** [comment]
Great point! 
We may consider quantization scheme as well [[ref](https://pytorch.org/docs/stable/quantization.html#quantized-tensor)]. This [REF](https://pytorch.org/docs/stable/quantization.html#quantized-tensor) considers different quantization parameters according to the quantization scheme; whether simple `float` / `int` **or** `lit of float`, `list of int` and `axis`.

**Comment by skykongkong8** [comment]
I was planning to bring up this issue after implementing a draft version of qint-using gemm algorithm, but here's a temporal one that I am using
```C++
template <typename T> struct ScalarIOQuantInfo {
  void operator=(ScalarIOQuantInfo& rhs) = delete; 
  inline ScalarIOQuantInfo() {}
  inline ~ScalarIOQuantInfo() {}

  inline ScalarIOQuantInfo(float a_sf, T a_zp) :
    activation_scale_factor(a_sf), activation_zero_point(a_zp) {}
  inline ScalarIOQuantInfo(float a_sf, T a_zp, float o_sf, T o_zp) :
    activation_scale_factor(a_sf),
    activation_zero_point(a_zp),
    output_scale_factor(o_sf),
    output_zero_point(o_zp) {
      compute_resultant_scale_factor();
      compute_resultant_zero_point();
    }
...
};

template <typename T> struct VectorIOQuantInfo {
...
};

...

typedef ScalarIOQuantInfo<uint8_t> QInfoU8;


```
