### ISSUE TITLE
Segfault happening in `classification_capi_func`

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#286]
segfault happening when there is no training set provided.

tested on TM1.

**Comment by kparichay** [comment]
`training data` is compulsory to be provided with `setConfig`.
My guess is the API/NeuralNetwork interface does not handle well if a `init/train` is called on a model where `setConfig` fails.

**Comment by jijoongmoon** [comment]
yes. if there is no training set, it fails. how did you test it?

**Comment by zhoonit** [comment]
I ran a test application on TM1 accidentally without training set
