### ISSUE TITLE
make nntrainer thread safe

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nntrainer#287]
Lets make nntrainer thread safe atleast from the API.

**Comment by zhoonit** [comment]
Do you have some kind of a road map or way to assure MT-safe?

**Comment by kparichay** [comment]
Needs to be at two levels -
- MT-safe primitives at the API level
- MT-safe primitives at NeuralNetwork class functions (if applications are allowed to use this directly). This reduces MT-safe overhead from other APIs.

**Comment by jijoongmoon** [comment]
I think this MT-safe is not urgent matter. We could do this next year or end of this year. But keep in mind.
