### ISSUE TITLE
nntrainer-application rpm has gtest dependency

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#289]
Does someone know if this is intended?

**Comment by jijoongmoon** [comment]
This issue is not relevant with nntrainer. You should ask it github.com/nnstreamer/nnstreamer/issues.

**Comment by zhoonit** [comment]
> This issue is not relevant with nntrainer. You should ask it github.com/nnstreamer/nnstreamer/issues.

Sorry, I misspelled it is about nntrainer-applications

**Comment by jijoongmoon** [comment]
well, nntrainer applications is for test nntrainer which includes unittest and sample application. gtest is required to test unit tests.
