### ISSUE TITLE
Make graph of layers

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nntrainer#346]
Currently, neural network represents the model as a vector of layers.
Need to upgrade to be a **Directed Acyclic Graph (DAG)** to represent a generic model.
Can also consider **Directed Cyclic Graph (DCG)** (with assumptions) as DAG does not support backward connections outside of RNN/LSTM kind of units.

**Comment by kparichay** [comment]
Support DAG - 
- [ ] Create TensorOps class
  - [ ] Layer extends TensorOps class
  - [ ] Update SharedTensor to include the number of tensors
  - [ ] Update signature of forward and backward, split applyGradients to be able to use in graph directly
- [ ] Choose backend library for graph
- [ ] Create a graph in model, with optimizer 
- [ ] Pass forward and backward arguments to graph and create entries in graph
- [ ] Store all the ops and tensors in a separate list
- [ ] Initialize ops in model.compile
- [ ] Initialize ops (allocate memory) in the first run
- [ ] Use topological sort for starters
- [ ] Modify topological sort to allow running multiple nodes in parallel

**Comment by jijoongmoon** [comment]
> Support DAG -
> 
> * [ ]  Create TensorOps class
>   
>   * [ ]  Layer extends TensorOps class
>   * [ ]  Update SharedTensor to include the number of tensors
>   * [ ]  Update signature of forward and backward, split applyGradients to be able to use in graph directly
> * [ ]  Choose backend library for graph
> * [ ]  Create a graph in model, with optimizer
> * [ ]  Pass forward and backward arguments to graph and create entries in graph
> * [ ]  Store all the ops and tensors in a separate list
> * [ ]  Initialize ops in model.compile
> * [ ]  Initialize ops (allocate memory) in the first run
> * [ ]  Use topological sort for starters
> * [ ]  Modify topological sort to allow running multiple nodes in parallel

I think it is good but We don't need to implement these right now. I think it is enough to have layer level graph to enable skip connection. Once we have layer level graph the we can regenerate graph according to tensor operation and optimize graph based on this tensor level detailed graph.

**Comment by jijoongmoon** [comment]
done with #712
