### ISSUE TITLE
Cannot install capi-nntrainer

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#357]
`rpm -i nntrainer` installs nntrainer
`rpm -i capi-nntrainer` fails to find dependency of nntrainr even though it is installed.

inside tizen
```sh
sh-3.2# rpm -i nntrainer-0.0.1-0.armv7l.rpm
        package nntrainer-0.0.1-0.armv7l is already installed
sh-3.2# rpm -i capi-nntrainer-0.0.1-0.armv7l.rpm
error: Failed dependencies:
        nntrainer=0.0.1-0 is needed by capi-nntrainer-0.0.1-0.armv7l
```
inside tizen

**Comment by myungjoo** [comment]
Add space:
```
Requires:        %{name}=%{version}-%{release}
```
==>
```
Requires:        %{name} = %{version}-%{release}
```
in the .spec file.

The rpmbuild has parsed the whole string ```%{name}=%{version}-%{release}``` as a required package name.

**Comment by zhoonit** [comment]
> Add space:
> 
> ```
> Requires:        %{name}=%{version}-%{release}
> ```
> 
> ==>
> 
> ```
> Requires:        %{name} = %{version}-%{release}
> ```
> 
> in the .spec file.
> 
> The rpmbuild has parsed the whole string `%{name}=%{version}-%{release}` as a required package name.

Helped a lot. Thanks!
