### ISSUE TITLE
Using DB for big data

### ISSUE THREAD

**Issue by jijoongmoon** [nnstreamer/nntrainer#37]
Instead of using files, It would be better to use data base system.

**Comment by myungjoo** [comment]
Because nntrainer's primary target device is embedded devices, DB should be chosen carefully and it might need to be optional. Note that relational DB (traditional SQL-based DBMSs) is way too heavy for the purpose. Plus, in many on-device training/retraining scenarios, data might be fed on line.

**Comment by jijoongmoon** [comment]
Dropped. Re-consider when it needed.
