### ISSUE TITLE
Model path shouldn't be described inside ini

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#370]
App developer cannot know the exact pathand allowed path of data (nor relative data path of the app). It is retrieved at [runtime](https://docs.tizen.org/iot/api/4.0/tizen-iot-headless/group__CAPI__APP__COMMON__MODULE.html#ga05b4b3b8fc58700720d8fa58004fc393)

So, we need to model path through capi rather than inside ini. 

I am wondering if we could quickly bump this and include it to ACR

**Comment by zhoonit** [comment]
I guess same applies for [DataSet] section.

**Comment by zhoonit** [comment]
Current workaround seems to change directory of a whole app. But it should better change root directory of the model instead

**Comment by kparichay** [comment]
If I understand your concern correctly, updating the model path is already support with `model.setProperty()`.
Regarding the [Dataset] section, when using the C-API, if the dataset file paths aren't decided, don't add dataset section in the ini, and rather create the dataset with the C-API using `ml_train_dataset_create_with_files()`.
Please once check. If this work, close this issue or elaborate more on the issue you faced.

**Comment by zhoonit** [comment]
> @zhoonit If I understand your concern correctly, updating the model path is already support with `model.setProperty()`.
> Regarding the [Dataset] section, when using the C-API, if the dataset file paths aren't decided, don't add dataset section in the ini, and rather create the dataset with the C-API using `ml_train_dataset_create_with_files()`.
> Please once check. If this works, close this issue or elaborate more on the issue you faced.

The point is fare enough. I just can't find the usage for [dataset], and [model path] section in ini file if that's the case though.

I am closing this issue.

**Comment by kparichay** [comment]
Yes, dataset paths and model path aren't very useful as they wont be static. However, at some point, these will be treated as folders with file names parsed and interpreted. Then, these can come in handy.
