### ISSUE TITLE
We should prohibit changing dataLen after it is copy constructed,

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#412]
this will lead to segfault, if dataLen is stretched. Because inner data won't resize anyway.

if datalen stretches, tensor itself should reassign and copy all the data. (Would that be contiguous? if setTensorDim has diffrent dimension?)

More than welcome to suggest ideas to alleviate this problem.

It can be a future problem.

**Comment by kparichay** [comment]
If the data is copy constructed/constructed in any manner, why is there any issue with resizing the data (delete existing data and alloc a new one?). This would require returning `const TensorDim` when inquiring about dimension from external user.
Changing dimension for a tensor would not be allowed - better to just straight up allocate a new tensor (reshaping would be allowed though).

**Comment by zhoonit** [comment]
> If the data is copy constructed/constructed in any manner, why is there any issue with resizing the data (delete existing data and alloc a new one?). This would require returning `const TensorDim` when inquiring about dimension from external user.

Yes. If dataLen changes, it should reallocate memory which is not there yet. It'd better throw error (or make a 🌵safeguard if dataLen changes) until it is implemented.

> Changing dimension for a tensor would not be allowed - better to just straight up allocate a new tensor (reshaping would be allowed though).

I am thinking about making reshape method with 🌵 attached. How's that?

**Comment by kparichay** [comment]
> I am thinking about making reshape method with cactus attached. How's that?

Sounds good to add reshape method.
It will be wrong to allow changing the dimension as other holders of this shared_ptr will not know that. Changing dataLen should always throw error.
