### ISSUE TITLE
Lazy tensor shouldnt copy by default

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nntrainer#422]
The input provided to the lazy tensor should not be copied by default.
The purpose of lazy tensor is to perform the operations lazily.
The caller wants a copy to be performed, then the caller should intentionally add a copy operation than expecting the lazy tensor to do it.

**Comment by zhoonit** [comment]
This can be done by passing already allocated memory slot

**Comment by kparichay** [comment]
We must think about if the lazy tensor is needed. If yes, then let's maintain it.
Yes, it can be done but changes the way it is being used everywhere, if any.

**Comment by zhoonit** [comment]
Closing, let's reopen when we happened to need this
