### ISSUE TITLE
Nondeterministic behavior on Databuffer

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#427]
When it runs to the full data(to the end), it sometimes returns -22 sometimes runs fine.

**Comment by kparichay** [comment]
@zhoonit Can you please once if this resolved on your side. Also please check if the un-deterministic beahvior of the example app is also fixed.

**Comment by zhoonit** [comment]
> @zhoonit Can you please once if this resolved on your side. Also please check if the un-deterministic beahvior of the example app is also fixed.

Yes I'll check with this PR

**Comment by zhoonit** [comment]
It is still Nondeterministic. reported here: https://github.com/nnstreamer/nntrainer/pull/428#issuecomment-689253629

**Comment by jijoongmoon** [comment]
closed by #525
