### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by jijoongmoon** [nnstreamer/nntrainer#443]
- [x] installation guide

- [x] Update Application guides including how to make input

   + [x] Classification 
   + [x] Training
   + [x] DeepQ Learning
   + [x] Tizen 
   + [x] Mnist 
   + [x] KNN
   + [x] Logistic Regression

**Comment by kparichay** [comment]
@jijoongmoon Please update which applications have been documented. If all are done, let's close this.
