### ISSUE TITLE
C-API: support remove layer 

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nntrainer#449]
Add support of C-API for removing a layer from a created model.
This will only be restricted to the last layer.

This is an intuitive for transfer learning.
- Remove existing last few layers
- Add new last few layers
- Retrain

**Comment by jijoongmoon** [comment]
If base model is tflite, then we need extra.

**Comment by kparichay** [comment]
Yes, with the last layer already removed, it can be done with ini file.
However, we need to support the scenario where the last layer is not already removed (which IMO is the general case).

**Comment by kparichay** [comment]
How about instead of adding `remove_layer`, we just support discarding the last layer while loading the model from ini?
Generic `remove_layer` add many complications about the connectivity of the graph when removing the layer.
Another alternate is `remove_last_layer` than giving the option while loading the model. However, I don't see any usecase for this API other than removing the last layer from an already loaded model.

**Comment by zhoonit** [comment]
> How about instead of adding `remove_layer`, we just support discarding the last layer while loading the model from ini?
> Generic `remove_layer` add many complications about the connectivity of the graph when removing the layer.
> Another alternate is `remove_last_layer` than giving the option while loading the model. However, I don't see any usecase for this API other than removing the last layer from an already loaded model.

I think it is a good approach though we need to verify that there exist only one last layer.

**Comment by zhoonit** [comment]
I think, we can make different ini load same model for transferlearning cases. (with same node identifier used to load the model)

**Comment by kparichay** [comment]
> > How about instead of adding `remove_layer`, we just support discarding the last layer while loading the model from ini?
> > Generic `remove_layer` add many complications about the connectivity of the graph when removing the layer.
> > Another alternate is `remove_last_layer` than giving the option while loading the model. However, I don't see any usecase for this API other than removing the last layer from an already loaded model.
> 
> I think it is a good approach though we need to verify that there exist only one last layer.

The layer will be removed by name. Last layer means that there is no operation layer after this (just loss layer after this layer.)
