### ISSUE TITLE
MNIST application is not deterministic

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nntrainer#464]
MNIST application with just fc layer and loss run over 10 times does not start from the same location.
This might be issue of data loading or network or some initialization and needs quick fix.

I think @zhoonit saw this kind of similar bug in his sample application too.

**Comment by kparichay** [comment]
This un-deterministic behavior is also there on `nntrainer_capi_nnmodel.train_with_file_01_p` unittest.

**Comment by kparichay** [comment]
@jijoongmoon If you have verified this, please close.

**Comment by jijoongmoon** [comment]
fixed by #522
