### ISSUE TITLE
PrintIfValid does more than it should

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nntrainer#467]
PrintIfValid calls setProperty().
This can lead to change in already set property value, or some property may not allow changes later.
PrintIfValid should not setProperty() but rather just print as all properties will always be valid. A property might be at default value but not invalid.

**Comment by zhoonit** [comment]
I think PrintIfValid is innocent rather problem is imposed in `setProperty(type, value)` 

`setProperty(type, value)` is used for validating if property type is valid when used without value argument.

**Comment by kparichay** [comment]
If `setProperty(type, value)` validates when with empty string, so, empty string as properties set by the user are just ignored without any warnings?

**Comment by zhoonit** [comment]
> If `setProperty(type, value)` validates when with empty string, so, empty string as properties set by the user are just ignored without any warnings?

It is known issue as of now. I decided not to ducktape with sth like `isPropertyValid` method to current implementation that will be scraped out sooner or later, rather decided to refactor altogether with property handler. Although, I won't be able to work on that until this September(I guess?).
If you think it is critical for now, I think it's okay to make a quick fix.

**Comment by kparichay** [comment]
Not urgent.
