### ISSUE TITLE
Support skip connections with user API

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nntrainer#469]
- [x] support skip connections with ini-file (https://github.com/nnstreamer/nntrainer/issues/239#issuecomment-659126498 and https://github.com/nnstreamer/nntrainer/issues/239#issuecomment-653440135)
- [x] update C-API to be able to add such models

**Comment by jijoongmoon** [comment]
done with #712

**Comment by kparichay** [comment]
Let's not close this till we have a graph example with API and able to create a skip connection with API.
