### ISSUE TITLE
Add training variable as an argument of forwarding or members of layer

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#506]
There are trainable to determine if a certain layer is trainable.

Another boolean is needed if current `forwarding` is done for training or for inferencing. 

For example, bn_layer has a different mechanism when training and inferencing. Currently, `trainable` is used to determine if it is in training mode. 

Semantically it is not right.

**Comment by kparichay** [comment]
Yes, `trainable` and `training`, there will be two different configurations.
Lets make sure to add good comments to differentiate the two.

**Comment by jijoongmoon** [comment]
Just for the TBD, there will be options to make layer trainable if user wants later. Say if convolution layer is set not to train, then update weight and calculation of delBias and delK could be skipped. In such cases, layer must be recognize it is trainable. But I think pooling is always not  trainable and should be give proper message to user. 

And inference option (such as is_trian) might be also required for using the different framework for inference to configure model differently. But it is not required now and removed #601. So let's close this issue.
