### ISSUE TITLE
Segfault when label is not properly given

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#511]
`label` should match num_classes with one-hot encoded format. If it is not, it crashes with segfault. e.g) label with `1 1 1 1 1 1 1...` I think there should be at least a safeguard to validate the given data.

**Comment by kparichay** [comment]
The label is not necessary to be always strictly one-hot encoded. There are multiple kinds of labels possible -
0. one-hot labels with a single value as 1, others are 0 - this is the base case which is used along with softmax
1. Sum of one-hot labels == 1 - allowing other labels which are similar to be non-zero but restricting sum to be 1
2. Sum of one-hot labels ~= 1 - this is softening 
3. Sum of one-hot labels > 1 - this is primarily used with multi-label classification where the last activation function is sigmoid (not softmax) allowing prediction of multiple labels to the same input.

Above is just a basic list for image classification when you assume that the label is a one-hot format. But for NLP or speech or even vision (segmentation/object detection), labels aren't one-hot. So, if you want to safeguard and validate label data, you need to ensure that the label is of one-hot label with 0. or 1. style.

**Comment by zhoonit** [comment]
> The label is not necessary to be always strictly one-hot encoded. There are multiple kinds of labels possible -
> 0. one-hot labels with a single value as 1, others are 0 - this is the base case which is used along with softmax
> 
> 1. Sum of one-hot labels == 1 - allowing other labels which are similar to be non-zero but restricting sum to be 1
> 2. Sum of one-hot labels ~= 1 - this is softening
> 3. Sum of one-hot labels > 1 - this is primarily used with multi-label classification where the last activation function is sigmoid (not softmax) allowing prediction of multiple labels to the same input.
> 
> Above is just a basic list for image classification when you assume that the label is a one-hot format. But for NLP or speech or even vision (segmentation/object detection), labels aren't one-hot. So, if you want to safeguard and validate label data, you need to ensure that the label is of one-hot label with 0. or 1. style.

Thank you for the detailed explanation.

If that's the case. it sounds like we need more sophisticated handling on the label data format. Maybe Getting the label type (from configuration) and verify?

**Comment by kparichay** [comment]
I don't know if label verification needs to be done.
Can you give some details about the segmentation fault with the labels as all you add above. That shouldn't happen. The training can diverge and values can go nan, but `segfault` is something different.

**Comment by zhoonit** [comment]
> I don't know if label verification needs to be done.
> Can you give some details about the segmentation fault with the labels as all you add above. That shouldn't happen. The training can diverge and values can go nan, but `segfault` is something different.

Current observation suggests that if the given label format is wrong(or different), it `segfaults`. That was why I thought a validation needs to be done. If validation is not required on the label, we need to fix the bug. I'll check more and make a reproducible example if possible.

**Comment by kparichay** [comment]
@zhoonit When you update support for changing label size based on input data for KNN, please check this issue as well.

**Comment by zhoonit** [comment]
Touched this issue, with dataset refactoring. This is now resolved
