### ISSUE TITLE
nntrainer nstreamer_filter test fail if default constructor of tensor.

### ISSUE THREAD

**Issue by jijoongmoon** [nnstreamer/nntrainer#535]
when we enable the unittest for nnstreamer, it fails.

@kparichay , could you look at this?

**Comment by kparichay** [comment]
@jijoongmoon I am unable to reproduce this issue on my system. Even with f8c4c6f merged, the unittest for nntrainer tensor_filter passes.

**Comment by jijoongmoon** [comment]
closed by #545
