### ISSUE TITLE
Include app test to gbs build

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#540]
Including app test to gbs build can prevent app crashing issues although it does not guarantee that app is running correctly.

**Comment by jijoongmoon** [comment]
yes. we need to check. But we need to modify the applications to make small enough to run for test.

**Comment by zhoonit** [comment]
@kparichay Could you check if #609 resolves this issue?

**Comment by kparichay** [comment]
Yes, #609 does important applications. Testing for others can be added later as those applications get more mature.
