### ISSUE TITLE
Question / Need Clarification: Tizen 6.0 M2 Release

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nntrainer#541]
Are you going to keep sending all commits into Tizen next-RC series?
or are you going to push hotfixes only to Tizen next-RC series?

If you are going to send hotfixes only to Tizen next-RC, you may need to create a release branch (e.g.. lts/X.Y or release/tizen6 or something forked from master)

**Comment by jijoongmoon** [comment]
I made release/tizen6.0 branch for hotfixes. We will push hotfixes.
