### ISSUE TITLE
Summary behavior of layer should not be in model

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nntrainer#583]
Summary behavior for layer is decided in model. Further, model summarization level decides what is summarized in layer.
Lets rather just use ml_train_summary_type_e in public functions and private functions can internally create and use enums.
Also, lets try to use enum class or if values are needed, lets use constexpr.

**Comment by zhoonit** [comment]
Summary will be done in two ways

1. using NN->print(int flag) 
bitfield is used to decide what to print.

2. using `NN->print_preset (enum preset)`
This accept a preset that presets bitfield and delegates to `print(int flag)`

**Comment by zhoonit** [comment]
reorganized with #605 later issue will be addressed with #608
