### ISSUE TITLE
Implement trainer bin with nnstreamer trainer bin

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#589]
Implement nnstreamer-trainer-filter in the easiest way to explore how the concept goes, what is required for the element.

Cc: @myungjoo

**Comment by myungjoo** [comment]
Evolution path?
1. start with nnstreamer custom filter.
1.5. reinforcement learning example pipeline.
2. make a gst-filter (tensor-*) that runs nntrainer in general
2.5. upgrade reinforcement learning example pipeline.
3. make a gst-filter (tensor-*) that runs training framework in general
4. supply related filters (DBsrc?)

**Comment by kparichay** [comment]
For any of them, you will have to think about looping on the data, in case training involves multiple epochs. There are a few options for this - 

1. Cache data internally in the element. Once a full epoch reached, then loop over it again and again. Issue - the only way for the current element to know that 1 epoch is finished is with EOS, and I am not sure if at the EOS stage, how long the element can run. This applies to a bin in pipeline which loops too. There is another issue, its not always possible or a good idea to cache the data.
2. Data is looped from outside the element by the pipeline. Some elements like `multifilesrc` support such features with properties like `loop`, but most of them don't. How will multiple source elements handle loop will have to be thought or if the pipeline with training is limited to just source elements which support `loop`.
3. The ML_API has a loop option that loops the pipeline externally over the same environment. This IMO is the worst of all three.
