### ISSUE TITLE
batch normalization not ready for inference

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nntrainer#597]
for batch normalization layer, in the inference/validation/test should set the trainable for the layer or the dependent parameter layer uses for checking if in train/eval mode should be flipped and flipped back in training.

**Comment by zhoonit** [comment]
JJ and I have discussed about this matter. We are gonna have a member is_training for each layer. How's this working for you?

**Comment by kparichay** [comment]
let's create a `ModelAttr` which contains certain attributes about the model, and the reference to this can be shared with all the layers, than all the layers having new members for such things.

**Comment by zhoonit** [comment]
> let's create a `ModelAttr` which contains certain attributes about the model, and the reference to this can be shared with all the layers, than all the layers having new members for such things.

Good idea
