### ISSUE TITLE
Add mode to ml_train_model_run

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nntrainer#606]
Add mode to ml_train_model_run with train and inference as the options.
Refer https://github.com/nnstreamer/nntrainer/pull/600#discussion_r494142824

**Comment by kparichay** [comment]
Note that for the inference option, there to be some interface to setup data for the inference run, or pass the data to the run method.

**Comment by zhoonit** [comment]
The requirement will be satisfied with ml_singleshot api. Please reopen if I got this wrong.
