### ISSUE TITLE
Adding flatten layer to cs slowing down significantly

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#611]
To make inference happening, I added flatten layer to the customshortcut.
1280:7:7:1 -> 1:62720:1:1

One epoch takes around 0.1s to 2sec (didn't exactly measure the time)

I guess there is memcopy happening around flatten layer??

**Comment by jijoongmoon** [comment]
Strange. I think there is not memcopy and only change dim in nntrainer. I guess there is problem with nnstreamer pipeline or something.

**Comment by zhoonit** [comment]
With flatten it took 13.86s without flatten it took 5.67s

**Comment by kparichay** [comment]
Does the final operation layer like fc etc when taking input with different shapes result in different performance?

**Comment by zhoonit** [comment]
You mean same fc layer with diffrent input shape? It seems like it.

**Comment by kparichay** [comment]
> You mean same fc layer with diffrent input shape? It seems like it.

Yes. But this is just a guess. Some in-depth checking is needed.

**Comment by kparichay** [comment]
I just checked model file from #612, fc layer receives the same shape tensor in both the cases. The issue is before the fc layer IMO.

**Comment by zhoonit** [comment]
with 13 more flatten layer, it does not change the result

below setup took 13.4467. So, I guess changing input shape might have affected the problem

```ini
[inputlayer]
Type = input
; Input_Shape = 1:1:62720	# Input Layer Dimension
Input_Shape = 1280:7:7	# Input Layer Dimension
Normalization = true

[flatten]
Type = flatten
[flatten1]
Type = flatten
[flatten2]
Type = flatten
[flatten3]
Type = flatten
[flatten4]
Type = flatten
[flatten5]
Type = flatten
[flatten6]
Type = flatten
[flatten7]
Type = flatten
[flatten8]
Type = flatten
[flatten9]
Type = flatten
[flatten10]
Type = flatten
[flatten11]
Type = flatten
[flatten12]
Type = flatten
[flatten13]
Type = flatten

[outputlayer]
Type = fully_connected
Unit = 2		# Output Layer Dimension ( = Weight Width )
bias_initializer = zeros
Activation = sigmoid 	# activation : sigmoid, softmax
Weight_Decay = l2norm
weight_Decay_Lambda = 0.005
```

**Comment by zhoonit** [comment]
I found the reason, it was related to resizing behavior in vector from `getDataFromBuffer()` I'll make a patch for the issue.

**Comment by zhoonit** [comment]
#626 resolves this issue.
On my machine,

Without the patch,

ini with `Input_Shape = 1:1:62720` took 2986ms,
ini with `Input_Shape = 1280:7:7` took 1487ms,

with this patch
ini with `Input_Shape = 1:1:62720` took 834ms,
ini with `Input_Shape = 1280:7:7` took 836ms,
