### ISSUE TITLE
Feature transformation and normalization methods

### ISSUE THREAD

**Issue by meteozay** [nnstreamer/nntrainer#637]
Hello,

Could you please implement feature centering and L2 normalization methods?

For details, please refer to Section 2.1 Feature Transformations of the following paper:

https://arxiv.org/pdf/1911.04623.pdf

Regards,

Mete.

**Comment by myungjoo** [comment]
@jijoongmoon Would this feature critical to our immediate products (2021 products) and clients? If so, we need to assign a committer and backlog it. If not, we can encourage the issuer @meteozay to implement his/her own and upstream it and help him implement one for nntrainer.

**Comment by jijoongmoon** [comment]
#859 will help
