### ISSUE TITLE
Add a version safeguard?

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#640]
Currently, unknown value  (e.g. LAYER_UNKNOWN) is the last number.

It will create a versioning problem. 

If we add a new layer (say `foo_layer`). It will have a number of old LAYER_UNKNOWN and will be interpreted differently in an older version.

But in older version will not have foo_layer, should this be alright?

Instead we put a version in our model format to mark which version is competible?

**Comment by kparichay** [comment]
yes, unknown must be set to a large number like `9999` .

**Comment by zhoonit** [comment]
As we are going toward the plugin-able architecture, this is no longer needed
