### ISSUE TITLE
Android build failed for KNN (missing libs folder?)

### ISSUE THREAD

**Issue by Seladam** [nnstreamer/nntrainer#646]
I'm having issues with compiling the KNN project with Android Studio. 

### **Preconditions:**
- Android Studio with the latest SDK (30) and NDK (21.3.6528147)

### **Build Steps**

**1. git clone https://github.com/nnstreamer/nntrainer
2. cd nntrainer
3. sudo apt install devscripts
4. sudo apt install tensorflow-lite-dev
5. meson build
6. ninja -C build**

![image](https://user-images.githubusercontent.com/36539179/96431764-4616ca80-1204-11eb-8619-0ee3014bed6b.png)

**7. Download and extract Gstreamer from:**
https://gstreamer.freedesktop.org/data/pkg/android/1.18.0/gstreamer-1.0-android-universal-1.18.0.tar.xz 
**8. Download and extract Tensorflow-lite android resources from nnstreamer-android-resource repository:**
https://raw.githubusercontent.com/nnstreamer/nnstreamer-android-resource/master/external/tensorflow-lite-1.13.1.tar.xz 
**9. Set environment variables:
9.1. sudo -H gedit /etc/environment
9.2. Add variables in new lines:**
```
ANDROID_NDK=/home/user/Android/Sdk/ndk/21.3.6528147
NNTRAINER_ROOT=/home/user/nntrainer
TENSORFLOW_ROOT=/home/user/Downloads/tensorflow-lite-1.13.1/tensorflow-lite
GSTREAMER_ROOT_ANDROID=/home/user/Downloads/gstreamer-1.0-android-universal-1.18.0
```
![image](https://user-images.githubusercontent.com/36539179/96439030-eb32a280-1206-11eb-9c06-0dc290b24f61.png)

**9.3. Save the file
9.4. Log out and log in to refresh the environment
10. Open the KNN project in Android Studio**

![image](https://user-images.githubusercontent.com/36539179/96439450-0a313480-1207-11eb-979a-94b9d50ed158.png)

**11. Set the NDK location in the PRoject Settings
11.1 File -> Project Structure...**

![image](https://user-images.githubusercontent.com/36539179/96440460-49ac5080-1208-11eb-8845-10b84228249a.png)

**11.2 SDK Loacation -> Android NDK location: select the installed ndk path**

![image](https://user-images.githubusercontent.com/36539179/96440444-444f0600-1208-11eb-947a-f5416766f66a.png)

**12. Make Project**

### **Results:**

![image](https://user-images.githubusercontent.com/36539179/96440811-c50e0200-1208-11eb-91c3-f2662032e740.png)
![image](https://user-images.githubusercontent.com/36539179/96441004-10281500-1209-11eb-98f2-932821d5a580.png)

In the Android.mk file at **line 42**, there is a reference to **libnntranier.so** with a path which doesn't exist.
`LOCAL_SRC_FILES := $(NNTRAINER_ROOT)/libs/$(TARGET_ARCH_ABI)/libnntrainer.so`
I don't have any **libs** folder in the nntrainer folder after cloning and building the repo.

**_What build command should I use to generate the libs folder? Or where should I look for it?_**

**Notes:**

- At line 50, there is also a reference to a .so file in the libs folder.
`LOCAL_SRC_FILES := $(NNTRAINER_ROOT)/Applications/utils/libs/$(TARGET_ARCH_ABI)/libapp_utils.so`
- I've found a libnntrainer.so file at: (NNTRAINER_ROOT)/build/nntrainer/libnntrainer.so. And I've also found a libapp_utils.so file at: (NNTRAINER_ROOT)/build/Applications/utils/jni/libapp_utils.so but i don't think that they are made for the arm64-v8a architecture. If I modify these two lines (42 and 50) to point to these files, I'll get a compiling error at the linking stage.
![image](https://user-images.githubusercontent.com/36539179/96442249-18814f80-120b-11eb-952d-40ce59013828.png)
![image](https://user-images.githubusercontent.com/36539179/96442188-01426200-120b-11eb-9827-63ca598a4d94.png)

### **Environment:**
- Ubuntu 18.04 (VirtualBox)
- Android Studio 4.1

**Comment by jijoongmoon** [comment]
You need to build nntrainer library for android first.
If you do
```
cd ${NNTRAINER_ROOT}/jni
ndk-build
 ```
then you will have libnntrainer.so in ```${NNTRAINER_ROOT}/libs/${TARGET_ARCH_ABI}/```
