### ISSUE TITLE
When section name is not unique, it is ignored

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#676]
for example, below example does not acknowledge the last layer
```ini
[model]
batch_size = 3
loss = cross
type = NeuralNetwork
optimizer = sgd
learning_rate = 0.1

[input]
input_shape = 1:1:3
type = input

[dense]
unit = 10
type = Fully_connected

[bn]
Type = batch_normalization

[act]
Type = Activation
Activation = sigmoid

[dense_1]
unit = 10
type = Fully_connected

[bn_1]
Type = batch_normalization

[act_1]
Type = Activation
Activation = sigmoid

[dense_2]
unit = 10
type = Fully_connected

[act_1]
Type = Activation
Activation = softmax
```

**Comment by kparichay** [comment]
IMO it is not ignore but rather the properties are overwritten with the latest values just as they should be.
Each section name marks a unique layer and redefining it overwrites the original section properties than creating a new one.
This is the behavior of ini.

**Comment by zhoonit** [comment]
> IMO it is not ignore but rather the properties are overwritten with the latest values just as they should be.
> Each section name marks a unique layer and redefining it overwrites the original section properties than creating a new one.
> This is the behavior of ini.

Even for that case, this is still an undefined behavior since it ignores the overwritten section.

**Comment by kparichay** [comment]
then I guess this is a bug in ini_parser.

**Comment by jijoongmoon** [comment]
I think we allow overwrite the property. if things go wrong then it is user's responsibility. ( And it is not possible if there is duplicated section name or not with iniparser ) If we want to, then we have to write our own parser I guess.
