### ISSUE TITLE
num_input, num_output is not needed after #671

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#679]
As vectors are used for num input and output after #671, having num input and output is redundant.

It should be changed to use `vector.size()` instead

**Comment by zhoonit** [comment]
@kparichay Could confirm if this is solved already? I feel like I have seen those are gone.

**Comment by kparichay** [comment]
`num_inputs` and `num_outputs` exist as properties. However, they are not stored internally as separate variables. Feel free to add a PR to remove them from properties :).

**Comment by kparichay** [comment]
This is resolved with layer_v2 branch.
