### ISSUE TITLE
Need to support multiple data set and require "input_layer" keyword for graph support.

### ISSUE THREAD

**Issue by jijoongmoon** [nnstreamer/nntrainer#682]
We need add "input_layer" keyword. We don't need kind of input_layer to specify next or previous layer so far because it's only one flat layers. However, we have to support multiple input and output, then we need "input_layers" keyword to specify previous layers and layer connections. 
 
Another issue we have we need to support multiple dataset and handle it like layer. (#681)

There is case which need multiple input. 
It might be like:

``` bash
[input_layer1]
Type = input
dataset = "dataset name1"
...

[input_layer2]
Type = input
dataset = "dataset name2"
...

[conv2d_layer]
Type = conv2d
input_layers = "input_layer1, input_layer2"
...
```
And then this will be
``` bash
[input_layer1]
Type = input
dataset = "dataset name1"
...

[input_layer2]
Type = input
dataset = "dataset name2"
...

[concat1]
Type = concat
input_layers ="input_layer1, input_layer2"

[conv2d_layer]
Type = conv2d
input_layers = "concat"
...
```

**Comment by kparichay** [comment]
Do we need to support multiple dataset or rather a single dataset should be capable to provide multiple inputs?
How about inside a dataset, we designate outputs and link them to input layers like in the example below:
```ini
[dataset]
...
outputs = "Image1"
outputs = "Image2"
outputs = "box"
label = "label"

[input_layer1]
...
input_layers = Image1

[input_layer2]
...
input_layers = Image2

[input_layer3]
...
input_layers = box
```
This would link the given outputs from a dataset to the specific input layer (dataset already supports multiple outputs, we just always use the first input). This design would reduce the number of datasets to just 1, which IMO is usually the way people store their dataset.

The below ini file will also be equivalent to the above ini as each input layer is mapped to the corresponding output of the dataset.
```ini
[dataset]
...
outputs = "Image1"
outputs = "Image2"
outputs = "box"
label = "label"

[input_layer1]
...

[input_layer2]
...

[input_layer3]
...
```

**Comment by kparichay** [comment]
As discussed offline with @jijoongmoon, maybe multiple datasets can be a single dataset with multiple input sources or multiple datasets sharing the same buffer in order to support shuffling.
