### ISSUE TITLE
A questions about input shapes.

### ISSUE THREAD

**Issue by meteozay** [nnstreamer/nntrainer#687]
Hi,

The CIFAR main.cpp code uses a mobilenetv2.tflite model that has an input dimension of (1, 84, 84, 3). 

We have a model which has the input dimension of (1, 3, 84, 84). We see that the tflite::label_image::read_bmp function reads the image as an uint8_t 1D array (line 163), then it is loaded into a tensor (line 172) and it will be passed to the model (line 175). 

My question is, how this 1D array/tensor is converted in the background to pass it to the model that has the input dimension of (1, 84, 84, 3)? Is it reshaped somehow that we cannot see? If our model requires input with (1, 3, 84, 84) dimension, should we change the read_bmp part?

Thank you.

Mete.

**Comment by kparichay** [comment]
@jijoongmoon can answer this.

**Comment by kparichay** [comment]
In my understanding, `read_bmp` does read image in format NHWC with shape `224, 224, 3` (check `decode_bmp`).
The application takes the dimension from tflite which is also of the format NHWC and is `1, 224, 224, 3`. 
The output from the model is `1, 7, 7, 1280` which is flattened.

NNTrainer requires with NCHW data format compared to tflite data format of NHWC. So, if you wish to pass `1,84,84,3` (NHWC) data to a model of input shape `1,3,84,84` (NCHW) or vice versa, you must transpose the input data.
