### ISSUE TITLE
Tizen Mirror Inconsistency

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nntrainer#706]
tizen branch in tizen.org is diverged from main branch since 

e3fc3a0f3af47a68639efb5667a1ec7f42004073 (tizen.org) vs 8232b8c198769e73c3c919aae6fbb9e3ab7cb92e (github.com)
Please fix the inconsistency and make them synchronized.

I recommend to keep "main" branch of tizen.org identical to "main" of github.com, leave tizen_6.0 as is, reset tizen branch of tizen.org (synchronized to main branch).

**Comment by jijoongmoon** [comment]
Done. thanks.
