### ISSUE TITLE
Ninja build fails on desktop

### ISSUE THREAD

**Issue by aladics** [nnstreamer/nntrainer#723]
I'm having issues compiling the source following the instructions given in the "Getting started" section of the readme. The build fails due to a missing header file: nnstreamer-single.h. It might be useful to mention that the last buildable version is: https://github.com/nnstreamer/nntrainer/commit/6c21da952eaf414eb468151c12257149f8a33d63 
OS version: Ubuntu 18.04.4

Steps to reproduce the error:
**1. Clone the latest version**
git clone https://github.com/nnstreamer/nntrainer.git
**2. Meson build**
cd nntrainer
meson build
**3. Ninja build**
ninja -C build

After this, the build fails with the following error message:
_[1/112] Compiling C++ object nntrainer...ntrainer_layers_nnstreamer_layer.cpp.o
FAILED: nntrainer/libnntrainer.so.p/_home_melo_work_sow30_test_nntrainer_nntrainer_layers_nnstreamer_layer.cpp.o 
c++ -Inntrainer/libnntrainer.so.p -Inntrainer -I../nntrainer -Iapi -I../api -I../api/ccapi/include -I../api/capi/include/platform -Inntrainer/dataset -I../nntrainer/dataset -Inntrainer/layers -I../nntrainer/layers -Inntrainer/models -I../nntrainer/models -Inntrainer/optimizers -I../nntrainer/optimizers -Inntrainer/tensor -I../nntrainer/tensor -Inntrainer/utils -I../nntrainer/utils -I/usr/include/x86_64-linux-gnu -I/usr/include/iniparser -I/usr/include/nnstreamer -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Werror -std=c++14 -g -DMIN_CPP_VERSION=201402 -Wredundant-decls -Wwrite-strings -Wformat -Wformat-nonliteral -Wformat-security -Winit-self -Waddress -Wno-multichar -Wvla -Wpointer-arith -Wno-error=varargs -O2 -ftree-vectorize -DUSE_BLAS=1 -D__LOGGING__=1 -DENABLE_TEST=1 -DENABLE_NNSTREAMER_BACKBONE=1 -DENABLE_TFLITE_BACKBONE=1 -fPIC -pthread -fopenmp -MD -MQ nntrainer/libnntrainer.so.p/_home_melo_work_sow30_test_nntrainer_nntrainer_layers_nnstreamer_layer.cpp.o -MF nntrainer/libnntrainer.so.p/_home_melo_work_sow30_test_nntrainer_nntrainer_layers_nnstreamer_layer.cpp.o.d -o nntrainer/libnntrainer.so.p/_home_melo_work_sow30_test_nntrainer_nntrainer_layers_nnstreamer_layer.cpp.o -c /home/melo/work/sow30/test/nntrainer/nntrainer/layers/nnstreamer_layer.cpp
In file included from /home/melo/work/sow30/test/nntrainer/nntrainer/layers/nnstreamer_layer.cpp:18:0:
../nntrainer/layers/nnstreamer_layer.h:19:10: fatal error: nnstreamer-single.h: No such file or directory
 #include <nnstreamer-single.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[2/112] Compiling C++ object nntrainer...r_nntrainer_layers_layer_factory.cpp.o
FAILED: nntrainer/libnntrainer.so.p/_home_melo_work_sow30_test_nntrainer_nntrainer_layers_layer_factory.cpp.o 
c++ -Inntrainer/libnntrainer.so.p -Inntrainer -I../nntrainer -Iapi -I../api -I../api/ccapi/include -I../api/capi/include/platform -Inntrainer/dataset -I../nntrainer/dataset -Inntrainer/layers -I../nntrainer/layers -Inntrainer/models -I../nntrainer/models -Inntrainer/optimizers -I../nntrainer/optimizers -Inntrainer/tensor -I../nntrainer/tensor -Inntrainer/utils -I../nntrainer/utils -I/usr/include/x86_64-linux-gnu -I/usr/include/iniparser -I/usr/include/nnstreamer -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Werror -std=c++14 -g -DMIN_CPP_VERSION=201402 -Wredundant-decls -Wwrite-strings -Wformat -Wformat-nonliteral -Wformat-security -Winit-self -Waddress -Wno-multichar -Wvla -Wpointer-arith -Wno-error=varargs -O2 -ftree-vectorize -DUSE_BLAS=1 -D__LOGGING__=1 -DENABLE_TEST=1 -DENABLE_NNSTREAMER_BACKBONE=1 -DENABLE_TFLITE_BACKBONE=1 -fPIC -pthread -fopenmp -MD -MQ nntrainer/libnntrainer.so.p/_home_melo_work_sow30_test_nntrainer_nntrainer_layers_layer_factory.cpp.o -MF nntrainer/libnntrainer.so.p/_home_melo_work_sow30_test_nntrainer_nntrainer_layers_layer_factory.cpp.o.d -o nntrainer/libnntrainer.so.p/_home_melo_work_sow30_test_nntrainer_nntrainer_layers_layer_factory.cpp.o -c /home/melo/work/sow30/test/nntrainer/nntrainer/layers/layer_factory.cpp
In file included from /home/melo/work/sow30/test/nntrainer/nntrainer/layers/layer_factory.cpp:31:0:
../nntrainer/layers/nnstreamer_layer.h:19:10: fatal error: nnstreamer-single.h: No such file or directory
 #include <nnstreamer-single.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[6/112] Compiling C++ object nntrainer...ainer_nntrainer_utils_parse_util.cpp.o
ninja: build stopped: subcommand failed._

**Comment by zhoonit** [comment]
Could you upgrade to the newest nnstreamer and nnstreamer-dev and try this again?

**Comment by aladics** [comment]
Thanks, that resolved the issue!
