### ISSUE TITLE
Save path has a default value

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#731]
Currently save_path has a default value when set from ini but we don't have default save_path when setting from a code.

```cpp
  model.save_path = iniparser_getstring(ini, "Model:Save_path", "./model.bin");
```

We have two options

1. moving default save_path to `Neuralnet::Constructor()`
2. remove default save_path

**Comment by zhoonit** [comment]
IMO, `2` is more appropriate. `save_path` should not be set implicitly because user should know about where they are saving the file (I guess we could warn user if save_path is not set instead).

Think about following scenario:
1. User create a model for a test and run. 
2. User changes the model slightly.
3. User runs the code and it will throw an error because previous data from `1` is left and it has wrong format.

**Comment by kparichay** [comment]
There is one more option:
3. Let default save_path will be random location. This ensures that multiple runs without save path dont continue train, but saves the model after training which can be retrieved after training. The random path can be of the format `/tmp/nnt_XXXXXX` 

This also solves the scenario described above.

**Comment by jijoongmoon** [comment]
> There is one more option:
> 3. Let default save_path will be random location. This ensures that multiple runs without save path dont continue train, but saves the model after training which can be retrieved after training. The random path can be of the format `/tmp/nnt_XXXXXX`
> 
> This also solves the scenario described above.

I think we need to set the limit of number of temp model file which is generated in contextAPP. I will be getting bigger and bigger

**Comment by zhoonit** [comment]
The issue is slowly coming to the ground as shown in #912.
Need discussion,

For the solution 3. It will be hard to delete or retrieve again if application is closed. If we have some feature like auto_saving, user will expect it to be retrieved when reopening the application, but in order to do that, they have to know the save_path.

I think if save_path is not given, we can just save it to memory as other frameworks do.
Instead we can ask user to call `saveModel` explicitly, which makes the model works in more expectable way.
It is expectable because if user runs a model again without saving it, it should give the same result.

**Comment by kparichay** [comment]
> For the solution 3. It will be hard to delete or retrieve again if application is closed. If we have some feature like auto_saving, user will expect it to be retrieved when reopening the application, but in order to do that, they have to know the save_path.

The default behavior should save only 1 file, in order to limit the memory usage. Plus this saved model will be printed in the log (just like in conventional frameworks) so that user can retrieve it if needed before system restart (/tmp will be emptied at system restart).

> I think if save_path is not given, we can just save it to memory as other frameworks do.

I dont understand, the model already exists in memory. I am not sure what save in memory.

> Instead we can ask user to call `saveModel` explicitly, which makes the model works in more expectable way.
> It is expectable because if user runs a model again without saving it, it should give the same result.

If `saveModel` is explicitly called, or saved to a random location, it will produce the same result, as running the model again will give the same result.

**Comment by zhoonit** [comment]
>  Plus this saved model will be printed in the log (just like in conventional frameworks) so that user can retrieve it if needed before system restart

We can print the log of a temporary but we don't know if other program or the same program restarted acknowledges it.
If it is user's responsibility to keep track of the temporary name, it is exactly the same as stating `save_path` explicitly, then there is no reason for user's to retrieve and use the information.
tmp will be emptied at system restart, but we don't know how many files will be created before system starts. We will not have control over the temporarily generated (and ditched) weights.

> saved to a random location, it will produce the same result, as running the model again will give the same result.

Also, we cannot deterministically mangle a temporary name just seeing a model1 file.

e.g) assuming model1.ini does not contain save_path and also user did not state through api.
1. program A trains model1.ini -> save_path /tmp/model1.ini
2. program B trains model1.ini -> save_path /tmp/model1.ini or newly generate a new save path? ?? 
what if program A and program B runs at the same time?

> I dont understand, the model already exists in memory. I am not sure what save in memory.
That's what I wanted to say. So if we don't save to a temporary file, it is already existing in the memory. My apologies for the unclear word choice.

**Comment by kparichay** [comment]
> Also, we cannot deterministically mangle a temporary name just seeing a model1 file.

A temporary name would be name generated by `mktemp`.

IMHO, if there is no saved path given by the user, we can just not save, or save to a new temporary name every time - it's just a choice to make for the framework. None of them is the wrong choice. 
However, the default save path must NOT be a fixed filename.
