### ISSUE TITLE
Features (Exceptions&Overheads) + Survey (Memory) Requests from Clients

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nntrainer#732]
Survey: this week.
Features: consider to include for 2021 development items

---

## Survey
- Peak Memory Consumption
    - With a Tizen GUI App
    - With a console App without UI

## Features
- Overhead (CPU/memory consumption) control based on the app status (Foreground/Background) or system status (user actively using it. user is leaving the device alone)
- Exception handling or checkpointing for a sudden power outage during trainig.

**Comment by myungjoo** [comment]
@jijoongmoon Please assign someone to measure peak memory consuption.

**Comment by lhs8928** [comment]
About Peak Memory Consumption survey:
With Cifar10 transfer learning without tflite the maximum resident set size is about 67Mb.
The reason why this much memory is required will be analyzed.

**Comment by myungjoo** [comment]
> About Peak Memory Consumption survey:
> With Cifar10 transfer learning without tflite the maximum resident set size is about 67Mb.
> The reason why this much memory is required will be analyzed.

Please describe the size of model and its structure as well.

**Comment by zhoonit** [comment]
For GUI application [here](https://github.com/nnstreamer/nntrainer/tree/main/Applications/Tizen_native/CustomShortcut)

## A. The application flow 

### 1. idle stage
App is launched but nothing has been done

### 2. drawing and feature extract
draw 10 samples to personalize and the feature is extracted with nnstreamer API, model is used [mobilenetv2.tflite](https://github.com/nnstreamer/nntrainer/tree/main/Applications/Tizen_native/CustomShortcut/res/mobilenetv2.tflite)

### 3. training
 Do training with nntrainer API

### 4. drawing + inferencing
 User draw one shot and do inference with nnstreamer API (pipeline tflite model and feed to nntrainer model)
### MISC.
Demonstration of drawing + feature extraction + training (stage 2 + stage 3)
![img](https://raw.githubusercontent.com/nnstreamer/nntrainer/main/docs/images/customshortcut_training.webp)

Demonstration of drawing + inferencing (stage 4)
![img](https://raw.githubusercontent.com/nnstreamer/nntrainer/main/docs/images/customshortcut_inference.webp)


## B. Test Setup

### Model / test input

- input: width=224, height=224, format = rgb, normalized to `[-1, 1]` -> 1:3:224:224
- feature extractor: mobilenetv2 model structure is lengthy so it is attached  (size of modelfile is 8.5M)
- output shape of feature_extractor: 1:7:7:1280
- nntrainer model (size of generated weights are 1.5M)
  - input shape of nntrainer model: 10:7:7:1280 (batched)
  - layer1 weight shape: [1:1:1:2, 1:1:62720:2]
  - weights from optimzier: [1:1:1:2, 1:1:62720:2]
  - output shape of nntrainer modle: 1:1:1:2

Everything is float32 (4bytes)

### Evaluation
The following script is used stage by stage, thus checking peak memory size throughout the app. 
```
curpid=$(ps -ef | grep example\.nntrainer | awk {'print $2'} | head -1)
while true; do
    sleep 1
    echo $(grep HWM /proc/${curpid}/status)
done
```

## C. 
[appendix.zip](https://github.com/nnstreamer/nntrainer/files/5535655/appendix.zip)
Result

### 1. idle stage
Profiled with turning app and wait.

Result: 31096 kB

### 2. drawing + feature extraction stage
Profiled when started drawing and doing feature extraction

Result: 60984 kB

### 3. Training
Profiled when training

Result: 60984 kB

### 4. drawing + inferencing
Profiled when inferencing (running tflite + nntrainer models at the sametime)

Result: 65340 kB

**Comment by lhs8928** [comment]
Peak memory Consumption about console App without UI
[Transfer Learning on Cifar Classification](https://github.com/nnstreamer/nntrainer/tree/main/Applications/TransferLearning/CIFAR_Classification) is used.

The memory consumptions is reduced to 40Mb after applying patch #755.

A. The application flow
	1. Extract feature
	Extract feature with tflite model mobilenetv2.tflite

	2. Training
	Do training with nntrainer API

B. Test Setup

input file: width=224, height=224, file type=bitmap(.bmp file)
feature extractor: mobilenetv2 model
input shape of FC layer=1:1:62720
# of classes(labels)=10
Everything is float32 (4bytes)

D. Analyze
	1. Weight of the FC layer: 62720 (input size) * 10 (output size) * 4 (type size) = 2450 KB
	2. Gradient of the FC layer(same size as weight) = 2450KB
	3. Adam optimizer weight (2 tensors with same shape as weight) = 4900KB
	4. Input = 32 (batch size) * 62720 (input size) * 4 (type size) = 7840KB


Evaluation
	The following is used to check memory size(Maximum resident set size)
	/usr/bin/time -v ./nntrainer_classification ../../res/Classification.ini ../../res/

**Comment by zhoonit** [comment]
Additional Survey on GUI application
Same setup as above here (https://github.com/nnstreamer/nntrainer/issues/732#issuecomment-726611894)

# Evaluation changed from the above
- Measured using smaps
- Measured _max_pss_ of ~all time~ current phase (idel, draw, eval, train...)
- Added per-library memory consumption
