### ISSUE TITLE
Handle continue_train semantics in correct way

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#736]
https://github.com/nnstreamer/nntrainer/pull/720#discussion_r521073037

when training.
1. `readModel()` should be called internally iff `continue_train` is true and hidden from users side

when inferencing
1. `readModel()` should be called if file does not exist raise an error.

@kparichay Please review 👍

**Comment by kparichay** [comment]
For inferencing - yes

For training - IMO readModel must be called to load the model weights but load training weights iff continue_train is true.
To not call readModel so as to training from scratch, either the save path file must be different (can add another property for it but I think file already exists/not is good enough)

**Comment by zhoonit** [comment]
This is handled with adding load/save api. The user requires to load explicitly if he wants to initiate weight with a certain weight file. Save_path only cares about saving
