### ISSUE TITLE
Layer ccapi needs forward / backward opened

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#750]
This is neccessary for the custom layer, If we can't have tensors inside ccapi, we could have float ** instead?

**Comment by kparichay** [comment]
For ccapi, exposing tensor is fine as it is planned to be done anyway.
But I think you might need float** with capi?
However, before finalizing any design, please conform to the updated design for forwarding/backwarding which might not take any input/output tensors (which will updated with graph PRs by @jijoongmoon).

**Comment by kparichay** [comment]
@zhoonit Please check if this is resolved with the updated layer design.

**Comment by zhoonit** [comment]
yes it is resolved :)
