### ISSUE TITLE
[API] Need major resturcturing on layer

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#756]
currently, layer.h does not give sufficient methods to create a custom layer although it should.  We will need a restructuring on the layer api

**Comment by jijoongmoon** [comment]
like what? Could you give use more specifics?

**Comment by zhoonit** [comment]
> like what? Could you give use more specifics?

For now, it is impossible to create a custom layer without using `layer_internal.h` 

1. because there are necessary members, for example, custom layer must have members like netbuffers, weights, flattens which can't be part of an api.
2. some required methods are omitted: forward, backward and how a user implement those without fully knowing our tensor (or expose tensor)
3. Arguably, some methods should be hidden from the api, for example getFlatten(), getName(), setTrainable(), getLoss()..

I am waiting for a design discussion but after the graph is finalized and merged :)

**Comment by zhoonit** [comment]
First, every other sources should be depending on layer.h only

**Comment by kparichay** [comment]
@zhoonit Please close this if it is resolved with LayerV2 design.

**Comment by zhoonit** [comment]
cool, I'll close this!
