### ISSUE TITLE
Support NNAPI as backend

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nntrainer#773]
Explore the support for NNAPI as backend "for training" for best android performance.

**Comment by zhoonit** [comment]
This is explored and found it not so applicable to our usage.

One main reason is that weights are assumed to be immutable inside nnapi model.
So if we want to use nnapi as a backend, every single items should be inputs and outputs of nnapi.

As this would take much time to implement, other accl should be more applicable then  NNAPI, let's keep it closed and reopen once time has come.

**Comment by kparichay** [comment]
I wonder if the same issue about the weight being immutable might exist in other backends as well, as most of the backends focus support for inference only. If so, nntrainer architecture must be adapt for it.
