### ISSUE TITLE
Make padding zero cost

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nntrainer#825]
Lets make padding zero cost for pooling , convolution or any future layers.
Lets say convolution needs padding, then the input tensor `In_c` allocated for this must  be tensor of padded size (input shape  + padded). The previous layer which treats `In_c` as its output tensor will have the same memory but a tensor with different shape and stride (which does not include padding). In this way, once the previous layer fills in the output, convolution layer automatically receives padded input without any extra cost.

The same optimization will be done for pooling and for backwarding as well.
This not only reduces the cost of the memcopy of the padding but also the temporary memory allocation overhead and its corresponding rise in peak memory is also removed.

**Comment by kparichay** [comment]
@zhoonit If you are optimizing convolution layer, you can consider this after you benchmark which are the most time consuming operations. IMO, there are 3 operations, 1. padding, 2. im2col and 3. gemm itself. I think 2 and 3 are inevitable but with this optimization, 1. can be removed.

**Comment by zhoonit** [comment]
Yes I will do this :) 
Thanks for the suggestion!

**Comment by zhoonit** [comment]
>Yes I will do this :)

I have changed to avoid make an allocation for the padded tensor (32d0327)
This is applied im2col in #830
I will apply this for pooling as well

**Comment by zhoonit** [comment]
This is pending for the pooling layer, I'll deal with this
