### ISSUE TITLE
Manager must use copy constructor than shared_ptr

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nntrainer#831]
The manager must use copy constructor than a shared_ptr.
Using shared_ptr with manager means that the manager between the two models is intertwined. However, the two models.

It is allowed for models to use copy constructor to create a copy of the model, which would have them share the same manager.
In this case, modifying the model A would change the memory in the manager, invalidating model B and its manager.

Rather, if the manager is copy constructed, that would give the flexibility to use the same memory for the manager of both models A and B internally with same Tensor/shared_ptr<Tensor> but allow changes to the model/its manager without invalidating the other model.

**Comment by zhoonit** [comment]
Making clear from the offline discussion:

Manager can share weights to be used across model (but not gradient, in&outs which can be seen temporary) thus allowing reusing memory.
```cpp 
 Model A = Backbone;
 Model B = Backbone;
 Model C; (c is classifier)
 Model D; (d is another classifier)
 A.append(C);
 B.append(D);

 A.train();
 B.train();
```
Showerthoughts:
1. having a lock_guard style idiom to manage temporaries (gradient, in&outs).
2. gradient optimization can't be done at compile time in this case
