### ISSUE TITLE
c++17 has parellel version of algorithms

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#832]
Just and information as of now.

https://devblogs.microsoft.com/cppblog/using-c17-parallel-algorithms-for-better-performance/

**Comment by kparichay** [comment]
As nntrainer is updated to use C++17, using `std::execution::par_unseq` and `std::execution::par` can be done at critical paths for speedup.

**Comment by zhoonit** [comment]
Yes, let's delay this until we have benchmark setup though :)
