### ISSUE TITLE
LogisticRegression Error during forwarding the model.

### ISSUE THREAD

**Issue by lekogabi** [nnstreamer/nntrainer#850]
Dear NNTrainer Team!

My colleagues and I tried to run the LogisticRegression example:
https://github.com/nnstreamer/nntrainer/tree/main/Applications/LogisticRegression

The training part was running without problem (./nntrainer_logistic train ${res}/LogisticRegression.ini ${res}/dataset1.txt), the model.bin was generated.
But when we tried the testing part (./nntrainer_logistic inference ${res}/LogisticRegression.ini ${res}/test.txt), we got the following error:
"Error during forwarding the model"

We did not add anything to the implementation, we used freshly cloned codes.
Could you please investigate why could this error appear?
Thanks in advance!

Regards,
Gabor Leko

**Comment by jijoongmoon** [comment]
Sorry for late response.! 
This #852 will fix the problem.
Thanks.
