### ISSUE TITLE
How can I get nnstreamer-tensorflow-lite for tizen armv7l?

### ISSUE THREAD

**Issue by nscotto** [nnstreamer/nntrainer#851]
Hi,

I am trying to build nntrainer for tizen armv7l, so far I have been able to find most dependencies except nnstreamer-tensorflow-lite.
Is there any existing rpm out there?
Otherwise how can I build it?

I don't know exactly what is nnstreamer-tensorflow-lite that makes it hard to find solutions myself.

Thank you in advance for your help.

**Comment by jijoongmoon** [comment]
I wonder which version of tizen you use. nnstreamer-tensorflow-lite released through tizen release.
you can find latest package in this url.
http://download.tizen.org/snapshots/tizen/unified/latest/repos/standard/packages/armv7l/

**Comment by nscotto** [comment]
Thank I found this repository as well, it helps a lot!
It is for tizen 5.5, I just recompiled packages from 6.0 to match my image in the end.
