### ISSUE TITLE
Support for quantized models?

### ISSUE THREAD

**Issue by nscotto** [nnstreamer/nntrainer#854]
Does nntrainer support quantized models?

**Comment by kparichay** [comment]
Can you please elaborate on the kind of support you require, as there can be multiple user scenarios?
1. The model is quantized like TfLite/TensorFlow/PyTorch model and the application wants to train a part of the model like transfer learning. This is possible with NNTrainer - refer to https://github.com/nnstreamer/nntrainer/tree/main/Applications/TransferLearning examples.
2. You want to finetune a quantized model. This can be done with NNTrainer, however, converting the quantized model weights to floating-point will have to be done manually. This will be soon supported with NNTrainer as an API.
3. You want to quantize a model trained/finetuned with NNTrainer. This is not yet supported but it will be this year.

**Comment by nscotto** [comment]
Sorry for the late reply, I needed to discuss with the team to understand a bit more our needs.
I think what we'd like to know is whether nntrainer has to work with float32 (at the cost of some performances) or if it can train directly a quantized model, or maybe a mixture of both (like having non trainable part quantized and trainable part float32).
What isn't clear as well is wether there can be a difference in the format during inference and training.
Our goal is to get the best performances possibles and we'd like to minimize the use of float32.
