### ISSUE TITLE
in / out / weights shouldn't be allocated inside layer

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#856]
Since in / out / weights are managed outside, there shouldn't be any case of reallocating in / out / weights (const std::shared_ptr would do?).

**Comment by kparichay** [comment]
These objects can change, if model is allowed to change dynamically (and then initialize again before usage).
One of the examples is dynamically removing and freeing the memory associated with data augmentation layers.

**Comment by zhoonit** [comment]
> These objects can change, if model is allowed to change dynamically (and then initialize again before usage).
> One of the examples is dynamically removing and freeing the memory associated with data augmentation layers.

I guess weights are okay to change dynamically. I think in & out shouldn't since it interacts with each other.
I'll check data augmentation layer to get a better understanding

**Comment by kparichay** [comment]
Data augmentation layer PR is not finalized yet. I will finalize it today.
Data augmentation layer will follow the same semantics as any other layer.
However, it is supposed to be not present in the graph in inference mode (a quick workaround will be to have a no-op with data augmentation layers in inference stage but a user getting the graph might be confused looking at data augmentation layers being executed in inference stage).

**Comment by kparichay** [comment]
I think this is resolved with layer_v2?

**Comment by zhoonit** [comment]
This is a bit different story but I guess this can be closed as it is stale now.
