### ISSUE TITLE
Inplace to be a layer property

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nntrainer#867]
Each layer must support a property - `inPlace` - which must be set by the layer creator.
This tells the tensor manager if a certain layer **can** operate in place for the backwarding as well as forwarding.
Then there must be a `operatingMode` which when set to `inPlace` will make the layer operate in place (layer must operate out-of-place in debug mode) and memory optimizations can be done.

These are critical for data augmentation layers being added.

**Comment by kparichay** [comment]
Also support `skipOpitmize` property for a layer, which must be checked by the manager before performing various optimizations for it.

**Comment by zhoonit** [comment]
Also support `requireLabel` property for a layer, if this is on, label is somehow fed to the layer.

**Comment by kparichay** [comment]
Also support `isWorkingInPlace` which will be set if the layer is optimized for in-place operation.

**Comment by kparichay** [comment]
- leaving `skipOptimize` for later. For now, manager only performs in-place optimizations for the layer which can be controlled by the layer, and gradient/derivative optimizations can be controlled for the model
- `inWorkingInPlace` is also left to be added later when needed
