### ISSUE TITLE
RGB image management and intensity normalizations

### ISSUE THREAD

**Issue by lekogabi** [nnstreamer/nntrainer#882]
Dear NNTrainer Team!

Since the channel management in NNTrainer is NCHW, if I want to store RGB images in .dat files to use them to train a model, what would be the correct sequence of the RGB values? 
R,G,B,R,G,B,...,R,G,B, 
or 
R,R,...,R,G,G,...,G,B,B,...,B
?

And if I use the tflite::label_image::read_bmp function, should we store the RGB values in the uint8_t array the same way?

Another thing about the intensity normalizations: in the different NNTrainer examples, different intensity normalizations can be found. If I am right, there is at least one example with no intensitiy normalization, and still trains the model very well (MNIST). My question: is there any standard convention about the intensities that NNTrainer requires/prefers (e.g. [0,255], [0,1], ...)?

Thanks in advance!

Regards,
Gabor Leko

**Comment by kparichay** [comment]
@lekogabi Thanks for your query.

> My question: is there any standard convention about the intensities that NNTrainer requires/prefers (e.g. [0,255], [0,1], ...)?

The standard convention about input normalization varies from task and model. The two most common normalizations are to normalize the data between range `[0,1]` or `[-1,1]`, which is followed in the machine learning community. You can choose either of these or some other normalization. But there is no limitation to the normalization or range of intensities required/preferred by NNTrainer. NNTrainer provides input `normalization` and `standardization` as input layer properties to help with this too.

> And if I use the tflite::label_image::read_bmp function, should we store the RGB values in the uint8_t array the same way?

As `TfLite` handles data in the NHWC, the RGB values read from `tflite::label_image::read_bmp`, the read values will have to be transposed. The transposed data, in the `uint8_t` data type, will have to converted to the `float` data type before passing to NNTrainer.
Please refer to https://github.com/nnstreamer/nntrainer/blob/73cf422cb4d126d1883f45d9996be3396464a46b/Applications/TransferLearning/CIFAR_Classification/jni/main.cpp#L163-L173 for using read_bmp to load image data, converting to float and passing it to TfLite. If you want to pass the same data to NNTrainer, you just need a transpose to convert to NCHW format.

**Comment by kparichay** [comment]
@lekogabi did this work for you?

**Comment by kparichay** [comment]
Closing this for now. 
Please re-open this issue if it is not resolved.
