### ISSUE TITLE
Evaluate ResNet

### ISSUE THREAD

**Issue by jijoongmoon** [nnstreamer/nntrainer#904]

**Comment by zhoonit** [comment]
Additional todo regarding this item

- [ ] speed benchmark of other frameworks with same data.
<details> <summary> benchmark results </summary>

| framework            | batch_size | real time   |   data_size |
|----------------------|------------|-------------|------------|
| nntrainer(fake data) | 32         | 11m37.97926 |     512    |
| nntrainer(fake data) | 128        | 10m45.761   |      512    |

</details> 

- [ ] Create readme.md 
readme.md must cite resnet and cifar100.

**Comment by zhoonit** [comment]
Evaluating resnet done (checking speed hasn't been done but this can be done relatively easily later)

For the result please check out the [link](https://github.sec.samsung.net/jhoon-it-lee/cifar100_resnet/issues/5)

**Comment by kparichay** [comment]
@zhoonit The links are internal. Please check the permissions and open for outside if possible.
