### ISSUE TITLE
clean up gtest for the tests

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#910]
gtest seems not available in the tizen or possibly other normal platform, 
Also, we don't have need every main, we can replace it to gtest 
let's make gtest self-contained for portability

**Comment by zhoonit** [comment]
This wasn't happening as I found that problem underlies in unsolvable spot as of now.

**Comment by myungjoo** [comment]
1. gtest is available in both Tizen and Ubuntu.
2. it is recommended to do static build with gtest. Thus, for faster build, you can compile once, generate .o and link to every unittest executable (or reuse gtest.a if that's available).

**Comment by zhoonit** [comment]
Sorry for the vague statement.

1. gtest is available, but gtest.so is not available in the run environment.
2. Which is fine because we can link static, but meson internally links gtest -libgtest.a and -libtest.so in tizen. ('dependency('gtest') does this, need to survey more) 
    - One of the reason is that 'gtest-devel' in tizen has both .so and .a in the same directory
    - to remedy the problem, there is an option for meson to force link static library only but it is not supported in our meson version(==0.50)
