### ISSUE TITLE
There is no machine_learning.training feature selector in tizen studio

### ISSUE THREAD

**Issue by lhs8928** [nnstreamer/nntrainer#913]
In the tizen studio, there is no http://tizen.org/feature/machine_learning.trainging feature in mobile-6.0

Could I get help where to add those?

**Comment by myungjoo** [comment]
Do we have Tizen Studio released with Tizen 6.0 API rootstrap already?

**Comment by zhoonit** [comment]
> Do we have Tizen Studio released with Tizen 6.0 API rootstrap already? You need to check with Tizen Studio first.
Yes, as we can export `nntrainer.h` rootstrap is applied. It does not have a feature key in a clickable list.
