### ISSUE TITLE
Recommendation: Class Diagram

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nntrainer#95]
I'd like to recommend, with a tool, generate a class diagram from nntrainer, review the architecture.

I'm sure a few of "public" methods might need to be reclassified as "protected" and you might see a few architectural upgrades from it.

**Comment by kparichay** [comment]
This is now needed more than ever.
- [ ] Tensor class needs redesigning to support multiple backends or libraries to implement (allocators as well as operations)
- [ ] Layer, activation and optimizer classes needs a proper design pattern to accommodate more derivatives
- [ ] Data buffer already needs heavy changes #303

**Comment by myungjoo** [comment]
You can create a class diagram half-automatically (if not fully automatically) with proper tools. You don't need to do it manually when you already have a working code set.

**Comment by zhoonit** [comment]
@kparichay Can this be closed now?
