### ISSUE TITLE
Is it possible to create a custom loss layer?

### ISSUE THREAD

**Issue by Str4t0n** [nnstreamer/nntrainer#954]
We would like to create our custom loss layer, but it is currently not possible to do so (or we did not find a solution for it yet), because nntrainer automatically adds its own loss layer to the model.

<details> 
  <summary>We are looking for something like this: </summary>

```ini
[Model]
Type = NeuralNetwork
...
[input]
Type = input
....
....
[lossLayer]
Type = mycustomloss
```

```cpp
auto &app_context = nntrainer::AppContext::Global();
app_context.registerFactory(ml::train::createLossLayer<custom::MyCustomLoss>);
```
```cpp
// or isntead of inherited from the base layer class
class MyCustomLoss : public nntrainer::Layer { ... }

// we could derive from the loss layer
class MyCustomLoss : public nntrainer::LossLayer { ... }
```
</details>

So that the nntrainer will know that its not necessary to add its own loss layer at the end .

**Comment by zhoonit** [comment]
As of now, this is not directly supported although it will be with a abstractLossLayer to derive from.

Haven't tested but Below workaround should work.

<details>
<summary>implementing custom losslayer </summary>

1. apply #934 
1. implementing custom loss layer with type "loss"

```cpp
namespace custom  {
/// you could also derive from nntrainer::LossLayer
class MyCustomLoss : public nntrainer::Layer { 
  
  void forwarding(bool training) override {
     const Tensor &predicted = net_input[0]->getVariableRef(); // feature from the network can be accessed from here
     const Tensor &label = net_hidden[0]->getGradientRef(); // label can be accessed from here

    Tensor &hidden = net_hidden[0]->getVariableRef(); // loss calculated should go here

   /// do something
  }

  void calcDerivative() override {
     Tensor &ret_derivative = net_input[0]->getGradientRef(); // calculate derivative to this variable
     /// do something
  }
  const std::string getType() const override { return "loss"; }; // this hack the mechanism to detect loss layer.
}
}
```

</details>

<details>
<summary>using custom losslayer </summary>

1. do not add custom defined losslayer in the ini configuration

```ini
[Model]
Type = NeuralNetwork 
# don't type any loss here
...
[input]
Type = input
....
....
# [lossLayer] don't attach loss layer here
# Type = mycustomloss
```

2. do not register to the context

```cpp
// as type clashes, you won't be able to register the custom layer
// auto &app_context = nntrainer::AppContext::Global();
// app_context.registerFactory(ml::train::createLossLayer<custom::MyCustomLoss>);
```

3. instead directly create `std::unique_ptr<ml::train::Layer>` 
```cpp
std::shared_ptr<ml::train::Layer> layer = std::make_shared<custom::MyCustomLoss>(args..);
layer->setProperties(/*appropriate properties if needed */);
```

4. Preload model with the config, attach custom layer to the model
```cpp
auto model = ml::train::createModel(ml::train::ModelType::NEURAL_NET));
auto status = model->loadFromConfig(config_file); // this won't have loss attached
status = model->addLayer(layer);  // created from  #3    

/** run model.. */
```

</details>

**Comment by Str4t0n** [comment]
@zhoonit Thank you for the suggestion. It worked like a charm.

**Comment by zhoonit** [comment]
Great to hear :) I'll leave this opened to track implementing support for custom loss.

**Comment by zhoonit** [comment]
Finally, nntrainer supports custom loss layer. 
#1320 is the last PR for the demonstration :)

I'll close this PR when #1320 is merged.

**Comment by kparichay** [comment]
@zhoonit Can this be closed?

**Comment by zhoonit** [comment]
> @zhoonit Can this be closed?

yes
