### ISSUE TITLE
memory usage increasing with each inference

### ISSUE THREAD

**Issue by klmntoth** [nnstreamer/nntrainer#965]
After #880 each call to inference on the same model increases the memory usage. The memory used during inference is not freed after the inference is done. The used memory is not freed even after the model is deleted.

Example to reproduce: https://gist.github.com/klmntoth/cd47b6ce6830b89fe2c31b0284c13b71 replace the main.cpp in the MNIST example with this. This ends up using 318MB ram.

Running Valgrind's Massif tool shows that all of that is used up by [this](https://github.com/nnstreamer/nntrainer/blob/main/nntrainer/tensor/tensor.cpp#L162) allocation.
Massif output: https://gist.github.com/klmntoth/77e0bac1289534a554133f302569ec45

**Comment by kparichay** [comment]
Thanks for reporting the issue. I am looking into this and will make a patch for this soon.

**Comment by klmntoth** [comment]
Sorry I said it wrong in my original comment, the memory is not freed when the model is deleted.
Also, Thanks for the fast reply!

**Comment by kparichay** [comment]
I added #976 which resolves the memory allocation issue. The patch resolves memory being added again and again, with each inference or train run.

> Sorry I said it wrong in my original comment, the memory is not freed when the model is deleted.

I could reproduce this with the main branch latest commit. I verified with #976 that no such issue exist. The memory consumption with MNIST does not exceed 2MB on my local system for the code you shared.
I ran with a bigger model - number of filters in the MNIST model increased from 6 and 12 to 600 and 1200 to test the memory. Maximum memory after 1 run vs 1000 runs remained same (around 1.5GB).

Please let me know if #976 resolves the issues on your side. There are a couple more issues with memory allocation which are being tracked at #974. They will be resolved this week.

**Comment by klmntoth** [comment]
I tried #976 and it resolved the memory problem, Thank you!
