### ISSUE TITLE
model initialization affects other model's output

### ISSUE THREAD

**Issue by klmntoth** [nnstreamer/nntrainer#968]
In the same program, initializing a model from config file affects later initialized completely distinct model's output.

Code for reproduction: https://gist.github.com/klmntoth/683c93587fa1a10448aa378da6757b02 replace the main.cpp in the MNIST example with this. The 1st parameter is the config for the model used for inference and the 2nd one is used when you want to create a temporary model before the inference one.
At least `loadFromConfig`, `compile` and  `initialize` is needed to affect later models.

Output when no other model created during the program:
```
user@ubuntu:~/nntrainer/Applications/MNIST/jni
$ ../../../build/Applications/MNIST/jni/nntrainer_mnist ../res/mnist.ini
<N9nntrainer6TensorE at 0x556df0edfb10>
Shape: 1:1:1:10
0.02635908499 0.04622353613 0.04935754463 0.133278653 0.0256401822 0.05091776699 0.121910885 0.03119517304 0.4900222123 0.02509496175
-------
```

Output when another model created and destroyed before inference:
```
user@ubuntu:~/nntrainer/Applications/MNIST/jni
$ ../../../build/Applications/MNIST/jni/nntrainer_mnist ../res/mnist.ini ../../LogisticRegression/res/LogisticRegression.ini
<N9nntrainer6TensorE at 0x563cd6629160>
Shape: 1:1:1:10
0.04599161446 0.1225339025 0.02117709443 0.04546906427 0.1257448643 0.02843466774 0.5213316083 0.01993283816 0.03031309322 0.03907119483
-------
```

**Comment by jijoongmoon** [comment]
@klmntoth , Thanks for the issue. We checked your code.
We think it is normal behavior. NNTrainer uses a random number generator. So if you initialize the model after other_model, then the initialized value will be changed.
You can get the same results when you do initialization of other_model after initialization of model, then you can get the same results.

**Comment by kparichay** [comment]
"Random Number Generator (RNG)" generates same values when started with same seed, and is deterministic.
When you only initialize only 1 model vs 2 models, initializing the second model first results in initialization of the first model differently as they share the RNG. If you try and initialize the first model first and then the second model (as @jijoongmoon described), this will match with the scenario with just 1 model.
Please let us know if this answers your question.
