### ISSUE TITLE
CAPI support regarding appcontext

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#978]
Lists of possible API's. Some are useful, some are maybe too much and low priority.

1. set default working directory for the model
1. model, set appcontext
1. register custom layer

**Comment by kparichay** [comment]
We will have to think this through, as this creates a difference in semantics between the cc-api and capi (appcontext belongs to the model which is not ccapi does), and creates confusion among application developers.

**Comment by zhoonit** [comment]
I agree, we need some through discussion about this matter.
