### ISSUE TITLE
Different behavior semantics of tensor sum and average

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nntrainer#99]
Tensor class functions `sum` and `average` have different behaviors.
Taking an input of `B, H, W`, `sum` results in an output of shape `B, 1, 1` and `average` output is of shape `1, H, W`.
IMO, both these functions should follow the same semantics and give same output shape to avoid confusion and bugs.

If an operation needs different shape for its result, its better to do multiple calls to `sum(axis)` or `average(axis)`.
@jijoongmoon What do you think?

**Comment by jijoongmoon** [comment]
some of your opinions are implemented in PR #126. Take a look and give me  your opinion.

**Comment by kparichay** [comment]
It is alright.
`sum` and `average` are generic functions for the tensor which do not take axis as input argument. 
So, I think it is better for them to have the same output semantics to avoid confusion in usage.
Currently, `sum` sums to the batch size while `average` averages over the batch size.
I have created #146 for this. Please have a look.
