### ISSUE TITLE
Draw application unittest broken

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nntrainer#995]
Draw application unittest is broken with ninja test. There are two issues:
- environment variable is not set for ninja test
- once the environment variable is set, the test runs successfully but does not end.

**Comment by kparichay** [comment]
> once the environment variable is set, the test runs successfully but does not end.

It seems like an issue in nnstreamer or nntrainer's plugin of nnstreamer. The issue exists from `test_model()` function and the the code blocks indefinitely due to threads waiting for each - more details not available yet.

**Comment by zhoonit** [comment]
FYI, I cannot reproduce the issue with #994 test runs successfully.

**Comment by kparichay** [comment]
Then maybe the application not terminating upon its completion is limited to my system? I will investigate.

**Comment by kparichay** [comment]
Closing, verified with @zhoonit.
Only app_deepq failing now which is now tracked in #991.
