### ISSUE TITLE
[tizen] nnstreamer.ini conf makes unable to test sub-plugin.

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#997]
Currently, we have `nnstreamer-extra` is build-required for rpm.
bug gbs fail because tizen repo does not have nnstreamer-extra
`gbs build --define "unit_test 1"`

I wonder about the purpose of nnstreamer-extra. It just deletes `nnstreamer.ini` afaict

```spec
%if 0%{?unit_test}
BuildRequires:	nnstreamer-protobuf
BuildRequires:	nnstreamer-extra
BuildRequires:	gst-plugins-good-extra
BuildRequires:	python
%endif #unit_test
```

**Comment by kparichay** [comment]
Yes, the purpose of `nnstreamer-extra` is to make `nntrainer tensor-filter` available to `nnstreamer` without installing the `nntrainer tensor-filter`. So, for this `nnstreamer-extra` deletes the `nnstreamer.ini`, and with `nnstreamer.ini` gone, `nnstreamer` reads its environment variables (set by the spec file) to point where `nntrainer tensor-filter` is binary is.

**Comment by zhoonit** [comment]
I think #994 resolves the issue, without `nnstreamer-extra` test runs because it overrides the default filter directory.
I wonder if we could delete the package?
`nnstreamer-extra` is not packaged into tizen, so the `gbs build --clean --clean-repo --define "unit_test 1"` fails for now

**Comment by kparichay** [comment]
`nnstreamer-extra` was added to make the `nntrainer tensor-filter` unittests pass (`test/nnstreamer_filter_nntrainer/runTest.sh`).
I don't think #994 changes anything for it.

**Comment by zhoonit** [comment]
I see. If that's the case, to make `gbs --clean-repo --define "unit_test 1"` build, I think we can change the `runTest.sh` to not rely on the package as well (by setting envvars). Do you have any other suggestion?

**Comment by kparichay** [comment]
I just tried the below commands on my local system - 
```bash
$ sudo rm -rf ~/GBS-ROOT-Snapshot/
$ # comment the statement "BuildRequires: nnstreamer-extra" from packaging/nntrainer.spec
$ gbs build -A x86_64 --include-all --define "unit_test 1"
```

The result was that the unittest failed. Please check on your side. 
Note that the unittest which failed was run manually from the spec file.

**Comment by zhoonit** [comment]
sharing mine. do we have nnstreamer-extra packaged somewhere?
```bash
$ sudo rm -rf ~/${GBS_ROOT}
$ gbs build -A x86_64 --define "unit_test 1"
[    0s] on X86_64, no limit mem size
[    0s] Using BUILD_ROOT=/home/jlee/GBS-ROOT-latest/local/BUILD-ROOTS/scratch.x86_64.0
[    0s] Using BUILD_ARCH=x86_64:i686:i586:i486:i386:noarch
[    0s] 
[    0s] 
[    0s] SOUTHRIDGE-W started "build nntrainer.spec" at Wed Mar 10 05:20:40 UTC 2021.
[    0s] 
[    0s] 
[    0s] processing recipe /home/jlee/GBS-ROOT-latest/local/sources/tizen/nntrainer-0.1.1-0/nntrainer.spec ...
[    0s] init_buildsystem --configdir /usr/lib/build/configs --cachedir /home/jlee/GBS-ROOT-latest/local/cache --define unit_test 1 --repository /home/jlee/GBS-ROOT-latest/local/repos/tizen/x86_64/RPMS --repository http://download.tizen.org/snapshots/tizen/base/latest/repos/standard/packages/ --repository http://download.tizen.org/snapshots/tizen/unified/latest/repos/standard/packages/ /home/jlee/GBS-ROOT-latest/local/sources/tizen/nntrainer-0.1.1-0/nntrainer.spec ...
[    0s] initializing /home/jlee/GBS-ROOT-latest/local/BUILD-ROOTS/scratch.x86_64.0/.srcfiles.cache ...
[    0s] /usr/lib/build/createdirdeps --oldfile /home/jlee/GBS-ROOT-latest/local/BUILD-ROOTS/scratch.x86_64.0/.srcfiles.cache /home/jlee/GBS-ROOT-latest/local/repos/tizen/x86_64/RPMS
[    0s] /usr/lib/build/createrepomddeps --cachedir=/home/jlee/GBS-ROOT-latest/local/cache http://download.tizen.org/snapshots/tizen/base/latest/repos/standard/packages/
[    1s] /usr/lib/build/createrepomddeps --cachedir=/home/jlee/GBS-ROOT-latest/local/cache http://download.tizen.org/snapshots/tizen/unified/latest/repos/standard/packages/
[    2s] expanding package dependencies...
[    3s] expansion error
[    3s]   nothing provides nnstreamer-extra
[    3s] 
```

**Comment by kparichay** [comment]
please comment statement "BuildRequires: nnstreamer-extra" from nntrainer.spec.

**Comment by zhoonit** [comment]
Yes, I'll comment the package and manage the test fail issue within a new PR

**Comment by zhoonit** [comment]
This is waiting for nnstreamer/nnstreamer#3128

**Comment by zhoonit** [comment]
While waiting, SE guys asked me to build the coverage report by this week, the report was not building since last September.

So, I'm commenting the app test for now to get the coverage report and later uncomment it as a workaround.
